import json
import re

# Read arabic strings
with open('arabic_strings.txt', 'r', encoding='utf-8') as f:
    ar_strings = [line.strip() for line in f if line.strip()]

# Let's create a basic translation mapping. 
# Some common terms can be translated properly. 
# For everything else we can just do a very basic translation or keep it as is.
trans_dict = {
    'غرف واسعة': 'Spacious Rooms',
    'شقة بمفردك': 'Apartment for yourself',
    'حذف': 'Delete',
    'تم نسخ رقم المالك بنجاح': 'Owner number copied successfully',
    'إيليا ستيت': 'Ilia State',
    'حذف الشقة': 'Delete Apartment',
    'الحي السكني': 'District',
    'غرفة': 'Room',
    'هل أنت متأكد من حظر الطالب': 'Are you sure you want to block this student',
    'دقائق مشياً': 'Minutes walk',
    'رقم الشقة': 'Apartment Number',
    'أبحث عن شريك هادئ ومحترم لمشاركة شقة': 'Looking for a quiet and respectful roommate to share an apartment',
    'حجز شقة مباشرة': 'Direct Apartment Booking',
    'مجهزة بالكامل بالفرش والأجهزة الكهربائية وتضم': 'Fully equipped with furniture and appliances, includes',
    'تطبيق أبشر رائع جداً': 'Absher app is great',
    'دولار': 'Dollar',
    'تم استخدام المعاينة المحلية للصورة': 'Local image preview used',
    'تم إرسال ردك إلى الطالب بنجاح وتحديث المحادثة': 'Reply sent to student and chat updated',
    'دقائق': 'Minutes',
    'غير مدخن ، طالب هادئ ومحترم ، يحافظ على النظافة العامة والهدوء': 'Non-smoker, quiet student, maintains cleanliness and calm',
    'هل يناسبك معاينته غداً؟': 'Is it convenient for you to view it tomorrow?',
    'تم إضافة الطالب بنجاح': 'Student added successfully',
    'جامعة تبليسي الطبية': 'Tbilisi Medical University',
    'فوري': 'Immediate',
    'طلاب': 'Students',
    'حقيبة': 'Bag',
    'وتم إرسال إشعار آلي للطالب في الشات': 'Automated notification sent to student in chat',
    'استئجار مع شريك': 'Rent with a roommate',
    'غرف': 'Rooms',
    'غرف منفصلة ومريحة': 'Separate and comfortable rooms',
    'مصطفى علي': 'Mostafa Ali',
    'شقة طلابية فاخرة': 'Luxury Student Apartment',
    'تم حذف الطالب بنجاح': 'Student deleted successfully',
    'التخصص': 'Major',
    'تمت إضافة شقة سكنية جديدة للإيجار في حي': 'New residential apartment added for rent in district',
    'جاري ضغط ورفع صورة الخدمة': 'Compressing and uploading service image',
    'تم حذف الخدمة بنجاح': 'Service deleted successfully',
    'فشل في إضافة الخدمة': 'Failed to add service',
    'تم الرد': 'Replied',
    'يتضمن نموذج طلب للعميل': 'Includes customer request form',
    'تصفح قسم الخدمات للطلب والاستفسار مباشرة': 'Browse services section to request and inquire directly',
    'جاري التنفيذ': 'In Progress',
    'التبليسي الطبية': 'Tbilisi Medical',
    'هل أنت متأكد من رغبتك في حذف هذه الشقة؟': 'Are you sure you want to delete this apartment?',
    'هاتف المالك': 'Owner Phone',
    'الذي تريد إرساله للطالب': 'that you want to send to the student',
    'تم تحديث حالة الطلب إلى': 'Request status updated to',
    'إطلالة بنورامية': 'Panoramic view',
    'المحاكاة نشطة': 'Simulation Active',
    'مفروشة بالكامل': 'Fully Furnished',
    'إدارة أعمال': 'Business Administration',
    'بسعر': 'at price',
    'فشل رفع الصورة': 'Image upload failed',
    'نقطة إلى محفظتك': 'points to your wallet',
    'تمت إضافة خدمة طلابية جديدة': 'New student service added',
    'دقيقة': 'minute',
    'ديدوبي': 'Didube',
    'يرجى إدخال مبلغ صحيح أكبر من الصفر': 'Please enter a valid amount greater than zero',
    'ساعة': 'hour',
    'فشل الرفع': 'Upload failed',
    'يرجى تحديد محادثة أولاً': 'Please select a chat first',
    'مرحباً، أود حجز الاستوديو المودرن في شارع كوستافا بسعر': 'Hello, I would like to book the modern studio on Kostava Street for',
    'موعد الانتقال': 'Move-in date',
    'ميعاد': 'Date',
    'استخراج إقامة طلابية': 'Obtaining student residency',
    'تحدث الآن': 'Chat Now',
    'أمس': 'Yesterday',
    'رسالة جديدة': 'New Message',
    'تم إضافة': 'Added',
    'الاستوديو متاح حالياً ومفروش بالكامل': 'The studio is currently available and fully furnished',
    'الاستقبال والنقل من المطار': 'Airport reception and transfer',
    'جاري ضغط وتحميل الصورة للمستخدم': 'Compressing and uploading image for user',
    'جلَداني': 'Gldani',
    'مكتمل': 'Completed',
    'شهر': 'Month',
    'جامعة جورجيا': 'University of Georgia',
    'الآن': 'Now',
    'شقة مشتركة لـ': 'Shared apartment for',
    'تم حذف التنبيه بنجاح': 'Alert deleted successfully',
    'نقداً عند معاينة واستلام الشقة': 'Cash upon inspection and receiving the apartment',
    'هندسة حاسبات': 'Computer Engineering',
    'بالقرب من جامعة جورجيا': 'Near University of Georgia',
    'عفواً، رصيد الطالب غير كافٍ لهذه العملية': 'Sorry, student balance is insufficient for this operation',
    'صورة مرفقة من خدمة العملاء': 'Image attached by Customer Service',
    'متاتسميندا': 'Mtatsminda',
    'سحب نقاط': 'Withdraw points',
    'رد على': 'Reply to',
    'الدفع يتم نقداً عند الاستلام': 'Payment is cash on delivery',
    'لا يوجد تنبيهات عاجلة منشورة حالياً': 'No urgent alerts published currently',
    'تم إرسال ردك إلى الطالب وحفظه في السيرفر': 'Your reply was sent to the student and saved to server',
    'أنثى': 'Female',
    'صالة كبيرة للمذاكرة المشتركة': 'Large hall for joint study',
    'مثال': 'Example',
    'عمر خالد': 'Omar Khaled',
    'الشقة المحجوزة': 'Reserved apartment',
    'قريب من السوبرماركت': 'Close to supermarket',
    'خطأ': 'Error',
    'ذكر': 'Male',
    'ستوديو مثالي للطالب المنفرد الباحث عن الهدوء والتركيز في الدراسة ويحتوي على': 'Perfect studio for a single student looking for quiet study, includes',
    'غرفة في شقة': 'Room in apartment',
    'صورة مرفقة': 'Attached Image',
    'بلكونة واسعة جداً': 'Very large balcony',
    'هل أنت متأكد من حذف هذا الحي؟': 'Are you sure you want to delete this district?',
    'إساني': 'Isani',
    'تم رفع الصورة وإرسالها للطالب بنجاح': 'Image uploaded and sent to student successfully',
    'تمت إضافة الشقة بنجاح ونشرها في التطبيق': 'Apartment added and published in app successfully',
    'يرجى إدخال اسم الخدمة': 'Please enter service name',
    'تم اختيار الصورة ومُعاينتها بنجاح': 'Image selected and previewed successfully',
    'فيديو مرفق': 'Attached Video',
    'الطب البشري': 'Human Medicine',
    'مصر': 'Egypt',
    'ساعدني في العثور على سكن ومطابقة شريك سكن محترم خلال أيام قليلة وبكل سهولة، خدمة ممتازة': 'Helped me find accommodation and match a respectful roommate easily within days, excellent service',
    'عدد الغرف': 'Number of Rooms',
    'إشعار آلي': 'Automated Notice',
    'جاري تسجيل فويس نوت': 'Recording voice note',
    'المتاح للشريك': 'Available for partner',
    'فريق خدمة العملاء سريع جداً في الرد على الشات، والاستقبال من المطار كان في الموعد المحدد بكل احترافية وأمان': 'Customer service is fast to respond, and airport pickup was on time and professional',
    'مسح': 'Clear',
    'معدلة': 'Edited',
    'منذ': 'Since',
    'يمكننا تجهيز كافة الملفات لك': 'We can prepare all files for you',
    'التسجيل والنقل الجامعي': 'University registration and transfer',
    'مضى': 'Ago',
    'فرصة ممتازة لثلاثة أصدقاء طلاب': 'Excellent opportunity for three student friends',
    'جامعة تبليسي الحكومية': 'Tbilisi State University',
    'أدخل الرابط': 'Enter link',
    'مرحباً، قمت بتعبئة نموذج البحث عن شريك سكن، هل يوجد طالب متوافق معي حالياً؟': 'Hello, I filled the roommate search form, is there any matching student currently?',
    'تم خصم النقاط بنجاح': 'Points deducted successfully',
    'إصدار وثيقة العنوان المعتمدة في جورجيا': 'Issuing approved address document in Georgia',
    'فجراً، عدد': 'Dawn, count',
    'الأردن': 'Jordan',
    'خدمة طلابية جديدة متوفرة الآن': 'New student service available now',
    'تسجيل العنوان القانوني': 'Legal address registration',
    'وإغلاق الشات؟': 'and close chat?',
    'تم حذف الخبر بنجاح': 'News deleted successfully',
    'استفسار بخصوص أوراق تجديد الإقامة الطلابية المطلوبة هذا العام': 'Inquiry regarding student residency renewal documents required this year',
    'شات': 'Chat',
    'يوسف محمود': 'Youssef Mahmoud',
    'السعودية': 'Saudi Arabia',
    'تم خصم': 'Deducted',
    'هل أنت متأكد من رغبتك في مسح هذه الرسالة؟': 'Are you sure you want to delete this message?',
    'قيد المراجعة': 'Under Review',
    'هل أنت متأكد من رغبتك في حذف هذه الخدمة؟': 'Are you sure you want to delete this service?',
    'سارة محمد': 'Sara Mohamed',
    'تم رفع صورة الخبر بنجاح': 'News image uploaded successfully',
    'جامعة إيليا الحكومية': 'Ilia State University',
    'طلب خدمة': 'Service Request',
    'إدارة': 'Manage',
    'صورة بنجاح': 'Image successfully',
    'تدفئة مركزية دافئة': 'Warm central heating',
    'شارع بيكيني': 'Pekini Street',
    'حذف الخدمة': 'Delete Service',
    'الرد': 'Reply',
    'شارع كوستافا': 'Kostava Street',
    'صورة شقة': 'Apartment Image',
    'متصل': 'Online',
    'تم رفع': 'Uploaded',
    'حمام': 'Bathroom',
    'جاري ضغط ورفع': 'Compressing and uploading',
    'شكراً لكم، تم تأكيد موعد معاينة الاستوديو غداً صباحاً': 'Thank you, studio viewing confirmed for tomorrow morning',
    'صيانة كافة الأعطال والتوصيلات الكهربائية': 'Maintenance of all electrical faults and connections',
    'إجراءات القبول وتحويل الساعات بين الجامعات': 'Admission procedures and credit transfer between universities',
    'تم حذف هذه الرسالة من قبل خدمة العملاء': 'This message was deleted by customer service',
    'تمت إضافة الحي بنجاح': 'District added successfully',
    'إرفاق صورة': 'Attach Image',
    'نشطة في التطبيق': 'Active in App',
    'جاري تشغيل التسجيل الصوتي': 'Playing voice recording',
    'حمام مستقل': 'Independent bathroom',
    'لا يوجد أخبار أو تنبيهات منشورة حالياً': 'No news or alerts published currently',
    'خدمة العملاء': 'Customer Service',
    'أهلاً بك سارة في أبشر': 'Welcome Sara to Absher',
    'طريقة الدفع': 'Payment Method',
    'أبشر': 'Absher',
    'ستوديو منفرد هادئ': 'Quiet single studio',
    'مرحباً خالد، المطلوب شهادة طالب حديثة وكشف حساب بنكي وعقد السكن القانوني': 'Hello Khaled, required is a recent student certificate, bank statement, and legal housing contract',
    'أحمد جمال': 'Ahmed Gamal',
    'تم إضافة النقاط بنجاح': 'Points added successfully',
    'شروط الشريك': 'Partner Conditions',
    'بلكونة بإطلالة مفتوحة': 'Balcony with open view',
    'فني سباكة': 'Plumber',
    'دقائق مشياً عن حرم جامعة جورجيا': 'Minutes walk from University of Georgia campus',
    'جديدة': 'New',
    'اضغط لفتح الصورة بحجم كامل': 'Click to open image full size',
    'منتهي الصلاحية': 'Expired',
    'غرفة قريبة من الجامعة الميديكال': 'Room near the Medical University',
    'تم إضافة الجامعة بنجاح': 'University added successfully',
    'موعد الوصول': 'Arrival Time',
    'رابط مرفق': 'Attached Link',
    'السبب': 'Reason',
    'تم حذف الشقة بنجاح': 'Apartment deleted successfully',
    'النوع': 'Gender',
    'بلكونة واسعة': 'Spacious balcony',
    'شقة سكنية جديدة معروضة للإيجار': 'New residential apartment for rent',
    'فني كهربائي': 'Electrician',
    'مرفق': 'Attachment',
    'الرد على هذه الرسالة': 'Reply to this message',
    'تم حظر الطالب': 'Student blocked',
    'محظور': 'Blocked',
    'تم تحديث حالة طلبك': 'Your request status updated',
    'شقة': 'Apartment',
    'ميزة إرفاق الفيديو تحت التطوير حالياً، يمكنك إرفاق رابط صورة أو تحميل صورة مباشرة': 'Video attach feature is under development, you can attach a link or upload an image directly',
    'صباحاً': 'AM',
    'فاكي': 'Vake',
    'تمت أرشفة المحادثة بنجاح': 'Chat archived successfully',
    'نشط وفعال للطالب': 'Active and effective for student',
    'تم حذف الحي بنجاح': 'District deleted successfully',
    'هل أنت متأكد من رغبتك في حذف هذا الخبر نهائياً؟': 'Are you sure you want to permanently delete this news?',
    'وضع': 'Status',
    'مرحباً خدمة العملاء، قمت بتعبئة نموذج البحث عن شريك سكن لشقة في شارع بيكيني': 'Hello customer service, I filled out the roommate search form for an apartment in Pekini Street',
    'تم حذف الجامعة بنجاح': 'University deleted successfully',
    'يبعد': 'Away',
    'تم حذف الرسالة بنجاح': 'Message deleted successfully',
    'سابورتالو': 'Saburtalo',
    'شريك سكن': 'Roommate',
    'غرفة نوم خاصة ومفروشة ، حمام ومطبخ مشترك ، شرفة': 'Private furnished bedroom, shared bathroom and kitchen, balcony',
    'تم رفع صورة الخدمة بنجاح': 'Service image uploaded successfully',
    'تم تعديل الرسالة بنجاح': 'Message edited successfully',
    'فويس نوت صوتي مسجل': 'Recorded voice note',
    'تم إرسال التسجيل الصوتي بنجاح': 'Voice recording sent successfully',
    'هل أنت متأكد من حذف هذا الطالب نهائياً؟': 'Are you sure you want to delete this student permanently?',
    'جاري رفع صورة الخبر': 'Uploading news image',
    'تكييف وتدفئة': 'AC and Heating',
    'رقم': 'Number',
    'تجهيز أوراق الإقامة لأول مرة أو التجديد': 'Preparing residency papers for the first time or renewal',
    'خطأ غير معروف': 'Unknown Error',
    'حدث خطأ أثناء الاتصال بالخادم': 'Error connecting to server',
    'حمام وتوزيع ممتاز للغرف يضمن الخصوصية لكل طالب': 'Bathroom and excellent room distribution ensures privacy for each student',
    'غير محدد': 'Unspecified',
    'شقة ممتازة للطلاب في قلب تبليسي بالقرب من محطة مترو التكنيكال': 'Excellent student apartment in the heart of Tbilisi near Technical Metro Station',
    'يوم الخميس الساعة': 'Thursday at',
    '، معك خدمة عملاء تطبيق أبشر': ', with you is Absher app customer service',
    'ستوديو مودرن': 'Modern Studio',
    'مساحة واسعة وتضم': 'Spacious area includes',
    'طلب خدمة طلابية': 'Student Service Request',
    'نقطة من محفظتك': 'points from your wallet',
    'مرحباً': 'Hello',
    'تعديل نص الرسالة': 'Edit Message Text',
    'جامعة إيليا': 'Ilia University',
    'خيارات الشقق ممتازة ومفروشة بالكامل والأسعار مناسبة جداً لميزانية الطلاب في تبليسي': 'Apartment options are excellent, fully furnished and prices are very suitable for student budgets in Tbilisi',
    'حدث خطأ أثناء الاتصال بالخادم عند إضافة الخدمة': 'Error connecting to server when adding service',
    'تم نشر التنبيه بنجاح': 'Alert published successfully',
    'الجنسية': 'Nationality',
    'حمام مع إطلالة رائعة من البلكونة': 'Bathroom with wonderful view from balcony',
    'تم نشر الخبر بنجاح': 'News published successfully',
    'إضافة نقاط': 'Add Points',
    'شكراً جزيلاً على سرعة الرد والمساعدة في الإقامة': 'Thank you very much for the quick response and help with residency',
    'أمن على مدار': 'Security around',
    'الملاحظات': 'Notes',
    'تمت إضافة الخدمة بنجاح إلى قائمة الخدمات': 'Service added successfully to services list',
    'انتقال فوري': 'Immediate Move-in',
    'متاحة للطلب': 'Available for request',
    'تم حظر الطالب وإغلاق المحادثة بنجاح': 'Student blocked and chat closed successfully',
    'شرح تفاصيل السكن والحجز': 'Explain housing and booking details',
    'تجميع شباب': 'Group of Youth',
    'مرحباً خدمة العملاء': 'Hello Customer Service',
    'تصفح شاشات السكن للاطلاع على الصور والتفاصيل كاملة': 'Browse housing screens for photos and full details',
    'توفير سيارات مريحة لاستقبالك فور وصولك تبليسي': 'Provide comfortable cars for reception upon your arrival in Tbilisi',
    'تعديل الرسالة': 'Edit Message',
    'تم حظر هذا الحساب من قبل إدارة خدمة العملاء ولن يتم استقبال رسائل جديدة': 'This account has been blocked by customer service management and new messages will not be received',
    'إلى': 'To',
    'فتح المحادثة مع الطالب': 'Open Chat with Student',
    'مؤرشفة': 'Archived',
    'الجامعة': 'University',
    'الخدمة المطلوبة': 'Requested Service',
    'هل يوجد طالب متوافق معي حالياً جاهز للانتقال الفوري؟': 'Is there a matching student currently ready for immediate move-in?',
    'ريم أحمد': 'Reem Ahmed',
    'إصلاح تسريبات المياه والصيانة الصحية': 'Repairing water leaks and plumbing maintenance',
    'رابط موقع أو ملف أونلاين': 'Website link or online file',
    'دولار للشخص': 'Dollars per person',
    'حذف الرسالة': 'Delete Message',
    'هل أنت متأكد من رغبتك في حذف هذا التنبيه نهائياً؟': 'Are you sure you want to permanently delete this alert?',
    'خالد عبد الله': 'Khaled Abdullah',
    'مصعد يعمل': 'Working Elevator',
    'هل أنت متأكد من حذف هذه الجامعة؟': 'Are you sure you want to delete this university?',
    'منذ ساعتين': 'Two hours ago',
    'نعم': 'Yes',
    'إنترنت ألياف ضوئية سريع': 'Fast Fiber Optic Internet',
    'وضع التخزين المحلي التفاعلي': 'Interactive Local Storage Mode'
}

with open('backend_php/admin/lang.js', 'r', encoding='utf-8') as f:
    js_content = f.read()

match = re.search(r'const translations = (\{.*?\});\n\nlet currentLang', js_content, re.DOTALL)
if match:
    json_str = match.group(1)
    data = json.loads(json_str)

    # Make keys for these based on english hash or just arbitrary
    for idx, ar_val in enumerate(ar_strings):
        if len(ar_val) > 2:
            en_val = trans_dict.get(ar_val, ar_val)
            # Find a safe key string (alphanumeric only) from english value
            key = 'mock_' + re.sub(r'[^a-zA-Z0-9]', '_', en_val)[:20].lower() + '_' + str(idx)
            data['ar'][key] = ar_val
            data['en'][key] = en_val

    new_json_str = json.dumps(data, ensure_ascii=False, indent=4)
    new_js = js_content.replace(json_str, new_json_str)

    with open('backend_php/admin/lang.js', 'w', encoding='utf-8') as f:
        f.write(new_js)
    
print('Added all mock data to translations!')
