import 'package:flutter/material.dart';

class LanguageService {
  // 'ar' = العربية, 'en' = الإنجليزية, 'ka' = الجورجية
  static final ValueNotifier<String> currentLang = ValueNotifier<String>('ar');

  static bool get isRtl => currentLang.value == 'ar';
  static TextDirection get textDirection => isRtl ? TextDirection.rtl : TextDirection.ltr;

  static final Map<String, Map<String, String>> _translations = {
    'ar': {
      'app_title': 'أبشر (ABSHER)',
      'welcome': 'مرحباً بك،',
      'home': 'الرئيسية',
      'services': 'الخدمات',
      'chat': 'المحادثة',
      'offers': 'عروض السكن',
      'profile': 'حسابي',
      'change_lang': 'تغيير لغة التطبيق (Language)',
      'lang_desc': 'العربية / English / ქართული (تحت التطوير)',
      'logout': 'تسجيل الخروج من الحساب',
      'guest_logout': 'الخروج للعودة لتسجيل الدخول',
      'guest_mode': 'أنت تتصفح حالياً كزائر!',
      'roommate_match': 'تجميع الطلاب في شقة مشتركة 🤝',
      'roommate_desc': 'سجل اسمك وجامعتك، وسيتواصل معك الدعم لتجميعك مع زملاء متوافقين.',
      'quick_services': 'الخدمات الطلابية السريعة ⚡',
      'view_all': 'عرض الكل',
      'browse_apts': 'تصفح الشقق السكنية المتاحة للطلاب 🏠',
      'no_commission': 'عروض طلابية مباشرة ومجهزة 🔥',
      'cash_payment': 'دفع نقدي (Cash) آمن عند الاستلام',
      'my_bookings': 'حجوزاتي وطلباتي السابقة',
      'payment_method': 'طريقة الدفع في أبشر',
      'contact_support': 'التواصل المباشر مع الدعم',
      'about_app': 'عن تطبيق أبشر (ABSHER)',
      'splash_subtitle': 'أبشر - رفيقك الطلابي الأول في جورجيا',
      'skip_to_start': 'تخطي إلى البداية >>',
      'login_fail': 'فشل تسجيل الدخول. تأكد من صحة البيانات.',
      'login_welcome': 'مرحباً بك في أبشر (ABSHER)',
      'login_subtitle': 'سجل دخولك للوصول إلى السكن الطلابي والخدمات في جورجيا',
      'email_or_phone': 'البريد الإلكتروني أو رقم الهاتف',
      'please_enter_email': 'يرجى إدخال البريد أو رقم الهاتف',
      'password': 'كلمة المرور',
      'please_enter_password': 'يرجى إدخال كلمة المرور',
      'contact_support_pw': 'تواصل مع الدعم عبر انستجرام @absher_georgia لاستعادة الحساب',
      'forgot_pw': 'نسيت كلمة المرور؟',
      'login_btn': 'تسجيل الدخول',
      'enter_as_guest': 'الدخول كزائر واستكشاف التطبيق',
      'no_account_yet': 'ليس لديك حساب طالب بعد؟',
      'create_new_account': 'إنشاء حساب جديد',
      'guest_name': 'زائر كريم',
      'guest_uni': 'تصفح عام (ضيف)',
      'other_uni_manual': 'أخرى (إدخال يدوي)',
      'register_fail': 'فشل إنشاء الحساب. تأكد من البيانات.',
      'create_account_title': 'إنشاء حساب طالب جديد',
      'create_account_subtitle': 'انضم إلى أسرة أبشر واستفد من كافة خدماتنا في جورجيا',
      'full_name': 'الاسم الكامل',
      'required_field': 'مطلوب',
      'email': 'البريد الإلكتروني',
      'invalid_email': 'بريد غير صالح',
      'phone_example': 'رقم الهاتف (مثال: 995555123456+)',
      'georgia_uni': 'الجامعة في جورجيا',
      'uni_and_district': 'اسم الجامعة واسم الحي المنطقه',
      'please_enter_uni_dist': 'يرجى إدخال اسم الجامعة والحي',
      'pw_min_6': '6 أحرف على الأقل',
      'create_account_btn': 'إنشاء الحساب الآن',
      'already_have_account': 'لديك حساب بالفعل؟',
      'all_flats': 'جميع الشقق',
      'flat_alone': 'شقة بمفردك',
      'with_roommate': 'استئجار مع شريك',
      'all_districts': 'جميع الأحياء',
      'all': 'الكل',
      'select_rooms': 'اختر عدد الغرف...',
      'one_room': 'غرفة واحدة',
      'two_rooms': 'غرفتين',
      'three_plus_rooms': '3 غرف فأكثر',
      'filter_flats': 'تصفية الشقق',
      'rental_type': 'نوع الاستئجار:',
      'district': 'الحي:',
      'bedrooms': 'غرف النوم:',
      'bathrooms': 'الحمامات:',
      'distance_uni': 'المسافة للجامعات (مشياً):',
      '10_mins': '10 دقائق',
      '20_mins': '20 دقيقة',
      '30_mins': '30 دقيقة',
      'apply_filter': 'تطبيق التصفية',
      'cancel': 'إلغاء',
      'select_nearby_unis': '🎓 اختيار الجامعات القريبة (اختر جامعة أو أكثر)',
      'confirm_selection': 'تأكيد الاختيار',
      'search_flats': 'البحث في الشقق...',
      'no_results': 'لا توجد نتائج تطابق بحثك',
      'details': 'التفاصيل',
      'book_now': 'احجز الآن',
      'welcome_user': 'أهلاً بك،',
      'wallet_points': 'المحفظة والنقاط',
      'current_points_balance': 'رصيد النقاط الحالي',
      'points_usage_desc': 'يمكنك استخدام النقاط لدفع تكلفة الخدمات',
      'transaction_history': 'سجل العمليات والإشعارات',
      'no_previous_transactions': 'لا توجد عمليات سابقة',
      'default_student_name': 'طالب كريم',
      'default_student_uni': 'جامعة جورجيا',
      'create_account_now': 'قم بإنشاء حساب طالب الآن للاستفادة من كافة العروض وطلب تجميع الشقق.',
      'login_or_register': 'تسجيل الدخول / حساب جديد',
      'booking_status_subtitle': 'متابعة حالة شقتك أو طلب التجميع',
      'wallet_subtitle': 'متابعة الرصيد والدفع بالنقاط',
      'please_login_wallet': 'الرجاء تسجيل الدخول أولاً لاستخدام المحفظة',
      'support_subtitle': 'انستجرام @absher_georgia أو هاتفياً',
      'about_subtitle': 'الإصدار 1.0.0 - أبشر في جورجيا',
      'clicked_on': 'تم النقر على:',
      'available_options': 'الخيارات المتاحة',
      'furnished_equipped': 'شقق مفروشة ومجهزة ✔️',
      'no_matching_flats': 'لا توجد شقق مطابقة حالياً في هذه القائمة.',
      'go_back': 'العودة للخلف',
      'immediate_move_in': 'انتقال فوري ⚡',
      'click_to_view_images': 'انقر لمعاينة الصور وحجز الشقة >>',
      'apartment_details': 'تفاصيل السكن',
      'images_count': 'صور',
      'apartment_number': 'شقة رقم #',
      'proximity_label': 'القرب:',
      'close_to_unis': 'قريبة من الجامعات الرئيسية',
      'roommate_reqs_title': 'استئجار مع شريك (بيانات ومواصفات الشريك المطلوب):',
      'roommate_reqs': '👤 شروط ومواصفات الشريك:',
      'roommate_facilities': '🏠 المساحة والمرافق المتاحة للشريك:',
      'features_and_facilities': 'المميزات والمرافق المتوفرة',
      'great_features': 'مميزات رائعة',
      'apartment_description': 'وصف السكن',
      'guest_alert_title': 'تنبيه 🔒',
      'guest_alert_body_booking': 'عفواً، لا يمكنك طلب حجز أو إرسال طلب سكن إلا بعد تسجيل الدخول كطالب في التطبيق.',
      'guest_alert_body_roommate': 'عفواً، يجب تسجيل الدخول أو إنشاء حساب طلابي أولاً لتتمكن من إرسال طلب البحث عن شريك سكن!',
      'choose_housing_method': 'اختر طريقة السكن المناسبة لك',
      'housing_method_desc': 'يمكنك حجز شقة كاملة بمفردك أو تعبئة نموذج البحث عن شريك سكن ليقوم الدعم بمطابقتك.',
      'browse_flats': 'تصفح الشقق',
      'browse_flats_desc': 'استعرض قائمة الشقق السكنية المتاحة للطلاب مع كافة الصور والأسعار.',
      'all_available_flats': 'جميع الشقق المتاحة',
      'all_available_flats_desc': 'قائمة بكافة الشقق السكنية المتاحة للطلاب مع كافة التفاصيل والأسعار.',
      'flat_room_choice': 'اختيار غرفه فى شقه',
      'flat_room_desc': 'عرض قائمة الشقق والاستوديوهات المناسبة لسكن شخص واحد بمفرده.',
      'flats_for_one': 'شقق تناسب شخص بمفرده',
      'flats_for_one_desc': 'قائمة الشقق والاستوديوهات المخصصة والمناسبة لسكن طالب واحد فقط.',
      'roommate_form_title': 'نموذج البحث عن شريك',
      'roommate_form_desc': 'قم بتعبئة بياناتك ليقوم فريق أبشر بمطابقتك مع الشريك الأنسب:',
      'full_name_label': 'الاسم الكامل',
      'nationality_label': 'الجنسية',
      'gender_label': 'النوع',
      'male': 'ذكر',
      'female': 'أنثى',
      'males_only': 'ذكور فقط',
      'females_only': 'إناث فقط',
      'university_label': 'الجامعة',
      'major_label': 'التخصص',
      'major_study_label': 'التخصص الدراسي',
      'whatsapp_number': 'رقم الواتساب',
      'whatsapp_contact_number': 'رقم هاتف التواصل (واتساب)',
      'when_move_in': 'متى تريد الانتقال؟',
      'move_in_date_label': 'موعد الانتقال المطلوب',
      'immediate_move': 'فوري / بأسرع وقت',
      'this_month_move': 'خلال هذا الشهر',
      'next_semester_move': 'مع بداية الفصل الدراسي الجديد',
      'choose_date': 'اختر تاريخ',
      'additional_notes': 'ملاحظات إضافية',
      'additional_notes_hint': 'ملاحظات إضافية (مثال: تفضيل التدخين، الهدوء، إلخ)',
      'send_to_customer_service': 'إرسال إلى خدمة العملاء',
      'send_roommate_request': 'إرسال طلب التجميع لفريق الدعم',
      'roommate_match_title': 'تجميع الطلاب في شقة مشتركة 🤝',
      'roommate_match_card_title': 'ابحث عن شريك سكن متوافق!',
      'roommate_match_card_desc': 'سجل بياناتك وميزانيتك، وسيقوم فريق أبشر بتجميعك مع طلاب من نفس جامعتك وتجهيز الشقة لكم.',
      'your_info_and_prefs': 'بياناتك والتفضيلات السكنية',
      'monthly_budget_usd': 'الميزانية الشهرية المقدرة للشخص (بالدولار USD)',
      'housing_type_req': 'نوع السكن المطلوب',
      'guest_alert_body_services': 'عفواً، يجب تسجيل الدخول أو إنشاء حساب طلابي أولاً لتتمكن من طلب الخدمات والصيانة الفورية!',
      'service_form_title': 'نموذج طلب خدمة (Service Form)',
      'service_form_desc': 'اختر الخدمة وتأكد من ملء بيانات الطلب:',
      'requested_service': 'الخدمة المطلوبة',
      'whatsapp_contact_short': 'رقم الواتساب للتواصل',
      'detailed_address': 'العنوان بالتفصيل',
      'best_time_to_execute': 'أفضل وقت للتنفيذ (من التقويم)',
      'attach_image_optional': 'إرفاق صورة للمشكلة (اختياري)',
      'image_attached_success': 'تم إرفاق صورة الخدمة ✔️',
      'cleaning_details_title': 'تحديد مساحة المنزل والتسعير التقديري (3 - 4 لاري لكل متر):',
      'number_of_rooms': 'عدد الغرف',
      'area_in_meters': 'المساحة (متر)',
      'estimated_cost': 'التكلفة التقديرية:',
      'currency_gel': 'لاري جورجي',
      'notes_details_hint': 'اكتب تفاصيل وملاحظاتك المحددة هنا...',
      'notes_and_details': 'ملاحظات وتفاصيل الطلب',
      'promo_code': 'كود الخصم (Promo Code)',
      'use_wallet_points': 'استخدام نقاط المحفظة للدفع',
      'submit_form_confirm': 'إرسال الفورم وتأكيد الطلب',
      'all_student_services': 'كافة خدمات أبشر الطلابية 🛠️',
      'instant_tag': 'فوري 📝',
      'request_service_button': 'طلب الخدمة 🛠️',
      'welcome_chat_msg': 'مرحباً بك في الدعم الفني المباشر لتطبيق أبشر 🌟! كيف يمكننا مساعدتك اليوم بخصوص السكن أو الخدمات في جورجيا؟',
      'rate_customer_service': 'تقييم خدمة العملاء',
      'rate_customer_service_desc': 'ما مدى رضاك عن سرعة وجودة التواصل مع الدعم الفني لـ أبشر؟ (الرؤية للأدمن فقط)',
      'additional_comments_hint': 'ملاحظات أو تعليقات إضافية...',
      'submit_rating': 'إرسال التقييم',
      'rating_success_msg': 'تم إرسال تقييمك لإدارة أبشر وحفظه بنجاح. شكراً لك!',
      'attach_link': 'إرفاق رابط 🔗',
      'enter_or_paste_link': 'أدخل أو الصق أي رابط لمشاركته في المحادثة:',
      'url_label': 'الرابط (URL)',
      'send_now': 'إرسال الآن',
      'attach_youtube_drive': 'إرفاق فيديو يوتيوب أو درايف 🎥',
      'enter_youtube_drive_link': 'أدخل أو الصق رابط فيديو من يوتيوب أو جوجل درايف:',
      'video_url_label': 'رابط الفيديو (URL)',
      'uploading_file_loading': 'جاري رفع وإرسال الملف... ⏳',
      'file_upload_success': 'تم رفع وإرسال الملف بنجاح! ✅',
      'file_upload_fail': 'عذراً، فشل رفع الملف إلى السيرفر ❌',
      'attach_media_chat': 'إرفاق وسائط للمحادثة 📎',
      'choose_image_gallery': '📷 اختيار صورة من المعرض',
      'choose_video_gallery': '🎥 اختيار فيديو من المعرض',
      'manual_link_input': '🔗 إدخال رابط ملف يدوي (موقع خارجي)',
      'preview_video_attachment': '🎥 معاينة الفيديو المرفق',
      'preview_image_attachment': '📷 معاينة الصورة المرفقة',
      'video_player_active': 'مشغل الفيديو نشط 🎥',
      'absher_support_chat_title': 'إدارة أبشر - الدعم والمحادثة',
      'rate_button': 'تقييم',
      'direct_call_snackbar': 'الاتصال الهاتفي المباشر أو عبر واتساب 995555123456+',
      'reply_to_message_selected': 'تم تحديد الرسالة للرد عليها 💬',
      'you': 'أنت',
      'tech_support': 'الدعم الفني',
      'click_to_play_video': 'انقر لتشغيل الفيديو',
      'reply_to_yourself': 'الرد على نفسك',
      'reply_to_support': 'الرد على خدمة العملاء',
      'attach_image_tooltip': 'إرفاق صورة',
      'attach_video_tooltip': 'إرفاق فيديو',
      'attach_link_tooltip': 'إرفاق رابط',
      'type_message_hint': 'اكتب رسالتك للإدارة هنا...',
      'sending_service_request': 'جاري إرسال طلب الخدمة... ⏳',
      'error_sending_service': 'خطأ في إرسال طلب الخدمة:',
      'auto_trans_1000': 'أبشر - Absher Georgia',
      'auto_trans_1001': '12:00 ظهراً',
      'auto_trans_1002': 'زائر',
      'auto_trans_1003': 'تنبيه هام',
      'auto_trans_1004': 'عفواً، يجب تسجيل الدخول أو إنشاء حساب طلابي أولاً لتتمكن من طلب حجز الشقق والسكن الطلابي!',
      'auto_trans_1005': 'إلغاء',
      'auto_trans_1006': 'تسجيل الدخول',
      'auto_trans_1007': 'أنت على وشك طلب رؤية ومعاينة: ',
      'auto_trans_1008': '. الدفع يتم نقداً عند الاستلام.',
      'auto_trans_1009': 'رقم هاتف التواصل (واتساب)',
      'auto_trans_1010': 'يوم المعاينة',
      'auto_trans_1011': 'الوقت المناسب',
      'auto_trans_1012': 'ملاحظات إضافية (مثال: نقطة التقاء محددة)',
      'auto_trans_1013': 'ملاحظة: أي تغيير أو تعديل في الموعد يتم بسهولة ومباشرة من خلال الشات مع خدمة العملاء.',
      'auto_trans_1014': 'جاري إرسال طلب الحجز... ⏳',
      'auto_trans_1015': 'لا يوجد',
      'auto_trans_1016': '💡 ملاحظة: الطالب يرغب برؤية الشقة في هذا الموعد، وأي تغيير في الموعد يتم التنسيق له عبر هذا الشات.',
      'auto_trans_1017': 'طالب أبشر',
      'auto_trans_1018': 'جامعة في جورجيا',
      'auto_trans_1019': 'تأكيد الطلب والانتقال للمحادثة الفورية 💬',
      'auto_trans_1020': 'تبليسي، جورجيا',
      'auto_trans_1021': 'شريك',
      'auto_trans_1022': 'الآن',
      'auto_trans_1023': 'الآن',
      'auto_trans_1024': 'الآن',
      'auto_trans_1025': 'الآن',
      'auto_trans_1026': 'طالب',
      'auto_trans_1027': 'جامعة في جورجيا',
      'auto_trans_1028': 'طالب أبشر',
      'auto_trans_1029': 'جامعة في جورجيا',
      'auto_trans_1030': 'تقييم ممتاز بدون ملاحظات إضافية',
      'auto_trans_1031': 'الآن',
      'auto_trans_1032': 'طالب',
      'auto_trans_1033': 'جامعة في جورجيا',
      'auto_trans_1034': 'إلغاء',
      'auto_trans_1035': 'إلغاء',
      'auto_trans_1036': '🎥 فيديو مرفق من الطالب',
      'auto_trans_1037': '📷 صورة مرفقة من الطالب',
      'auto_trans_1038': 'ستوديو',
      'auto_trans_1039': 'منفرد',
      'auto_trans_1040': '1 غرفة',
      'auto_trans_1041': 'خاصة',
      'auto_trans_1042': 'مشتركة لـ 3',
      'auto_trans_1043': 'أبشر',
      'auto_trans_1044': 'ميعاد',
      'auto_trans_1045': 'تاريخ',
      'auto_trans_1046': 'سبتمبر',
      'auto_trans_1047': 'آخر أخبار جورجيا 📰',
      'auto_trans_1048': 'تحديث الأخبار',
      'auto_trans_1049': 'لا توجد أخبار حالياً 📰',
      'auto_trans_1050': 'الآن',
      'auto_trans_1051': 'عروض الموسم الدراسي 🎓',
      'auto_trans_1052': 'احجز سكنك الطلابي الآن بسهولة وأمان!',
      'auto_trans_1053': 'دفع نقدي (Cash) آمن مباشرة عند استلام مفتاح شقتك في تبليسي.',
      'auto_trans_1054': 'عروض حصرية 🔥',
      'auto_trans_1055': 'سكن مشترك اقتصادي 🤝',
      'auto_trans_1056': 'تجميع الطلاب في شقق قريبة من الجامعات',
      'auto_trans_1057': 'وفر نصف القيمة الإيجارية وسجل اسمك ليقوم الدعم بمطابقتك مع زملاء متوافقين.',
      'auto_trans_1058': 'توفير 50% 💰',
      'auto_trans_1059': 'استقبال مطار ونقل جامعي 🚖',
      'auto_trans_1060': 'وصلت تبليسي حديثاً؟ نحن في استقبالك!',
      'auto_trans_1061': 'سيارات مريحة ومندوبين لمساعدتك في خطك الأول وتوصيلك حتى باب سكنك.',
      'auto_trans_1062': 'خدمة 24/7 ⚡',
      'auto_trans_1063': 'إقامات طلابية وتسجيل قانوني 🛂',
      'auto_trans_1064': 'تخليص كافة أوراقك الجامعية والقانونية',
      'auto_trans_1065': 'فريق متخصص لضمان سلامة وضعك القانوني وإقامتك في جورجيا بكل سهولة.',
      'auto_trans_1066': 'مضمون ومعتمد 📜',
      'auto_trans_1067': 'شقة طلابية فاخرة - شارع بيكيني (Pekini)',
      'auto_trans_1068': '450 دولار / شهر',
      'auto_trans_1069': 'سابورتالو (Saburtalo)',
      'auto_trans_1070': 'التبليسي الطبية TSMU (10 دقائق مشياً) | جامعة جورجيا UG (20 دقيقة)',
      'auto_trans_1071': 'شقة بمفردك',
      'auto_trans_1072': '3 أفراد (شقة كاملة)',
      'auto_trans_1073': 'شقة بمفردك',
      'auto_trans_1074': '2 حمام',
      'auto_trans_1075': '3 غرف واسعة',
      'auto_trans_1076': 'تدفئة مركزية دافئة',
      'auto_trans_1077': 'بلكونة بإطلالة مفتوحة',
      'auto_trans_1078': 'إنترنت ألياف ضوئية سريع',
      'auto_trans_1079': 'مفروشة بالكامل',
      'auto_trans_1080': 'شقة ممتازة للطلاب في قلب تبليسي بالقرب من محطة مترو التكنيكال. مجهزة بالكامل بالفرش والأجهزة الكهربائية مع إطلالة رائعة من البلكونة وتدفئة مركزية ممتازة للشتاء. الدفع يتم نقداً عند الاستلام.',
      'auto_trans_1081': 'ستوديو مودرن - بالقرب من جامعة جورجيا (UG)',
      'auto_trans_1082': '380 دولار / شهر',
      'auto_trans_1083': 'فاكي (Vake)',
      'auto_trans_1084': 'جامعة جورجيا UG (10 دقائق مشياً) | إيليا ستيت (15 دقيقة)',
      'auto_trans_1085': 'شقة بمفردك',
      'auto_trans_1086': '1 فرد (ستوديو منفرد)',
      'auto_trans_1087': 'شقة بمفردك',
      'auto_trans_1088': '1 حمام',
      'auto_trans_1089': 'ستوديو منفرد هادئ',
      'auto_trans_1090': 'تكييف وتدفئة',
      'auto_trans_1091': 'أمن على مدار 24 ساعة',
      'auto_trans_1092': 'قريب من السوبرماركت',
      'auto_trans_1093': 'ستوديو مثالي للطالب المنفرد الباحث عن الهدوء والتركيز في الدراسة. يبعد دقائق مشياً عن حرم جامعة جورجيا. أثاث حديث ومطبخ مجهز بالكامل.',
      'auto_trans_1094': 'شقة مشتركة لـ 3 طلاب - إطلالة بنورامية',
      'auto_trans_1095': '550 دولار (أو 180 دولار للشخص)',
      'auto_trans_1096': 'سابورتالو (Saburtalo)',
      'auto_trans_1097': 'إيليا ستيت Ilia (10 دقائق) | جامعة تبليسي الحكومية TSU (20 دقيقة)',
      'auto_trans_1098': 'استئجار مع شريك',
      'auto_trans_1099': '3 أفراد (شقة مشتركة)',
      'auto_trans_1100': 'غير مدخن ، طالب هادئ ومحترم ، يحافظ على النظافة العامة والهدوء',
      'auto_trans_1101': 'غرفة نوم خاصة ومفروشة ، حمام ومطبخ مشترك ، شرفة (بلكونة واسعة)',
      'auto_trans_1102': 'استئجار مع شريك',
      'auto_trans_1103': '2 حمام',
      'auto_trans_1104': 'غرف منفصلة ومريحة',
      'auto_trans_1105': 'صالة كبيرة للمذاكرة المشتركة',
      'auto_trans_1106': 'بلكونة واسعة جداً',
      'auto_trans_1107': 'مصعد يعمل 24/7',
      'auto_trans_1108': 'فرصة ممتازة لثلاثة أصدقاء طلاب أو لتجميع الطلاب. مساحة واسعة وتوزيع ممتاز للغرف يضمن الخصوصية لكل طالب.',
      'auto_trans_1109': 'ستوديو فاخر مستقل - شارع أغماشينيبلي',
      'auto_trans_1110': '400 دولار / شهر',
      'auto_trans_1111': 'ديدوبي (Didube)',
      'auto_trans_1112': 'مشياً إلى محطة المترو والجامعات (10 دقائق)',
      'auto_trans_1113': 'شقة بمفردك',
      'auto_trans_1114': '1 فرد',
      'auto_trans_1115': 'شقة بمفردك',
      'auto_trans_1116': '1 حمام',
      'auto_trans_1117': 'ستوديو مستقل لشخص واحد',
      'auto_trans_1118': 'تكييف وتدفئة',
      'auto_trans_1119': 'إنترنت سريع',
      'auto_trans_1120': 'أثاث جديد',
      'auto_trans_1121': 'شقة ستوديو خاصة لشخص واحد بموقع ممتاز بالقرب من الخدمات والمواصلات.',
      'auto_trans_1122': 'شقة مع شريك - سابورتالو بالقرب من الطبية',
      'auto_trans_1123': '220 دولار للشخص',
      'auto_trans_1124': 'سابورتالو (Saburtalo)',
      'auto_trans_1125': 'التبليسي الطبية TSMU (5 دقائق مشياً)',
      'auto_trans_1126': 'استئجار مع شريك',
      'auto_trans_1127': 'مطلوب شريك واحد سكن',
      'auto_trans_1128': 'طالب طب أو هندسة غير مدخن ومحافظ على الهدوء والنظافة',
      'auto_trans_1129': 'غرفة نوم كبيرة خاصة ومكيفة ، حمام ومطبخ مشترك مع طالب واحد فقط',
      'auto_trans_1130': 'استئجار مع شريك',
      'auto_trans_1131': '1 حمام',
      'auto_trans_1132': '1 غرفة نوم مستقلة للشريك',
      'auto_trans_1133': 'مطبخ مجهز',
      'auto_trans_1134': 'بلكونة هادئة',
      'auto_trans_1135': 'شقة ممتازة لطالب يبحث عن شريك سكن هادئ ومحترم على بعد خطوات من التبليسي الطبية.',
      'auto_trans_1136': 'الإشعارات والتنبيهات 🔔',
      'auto_trans_1137': 'لا توجد تنبيهات جديدة حالياً 🔕',
      'auto_trans_1138': 'الآن',
      'auto_trans_1139': 'الكل',
      'auto_trans_1140': 'التبليسي الطبية (TSMU)',
      'auto_trans_1141': 'جامعة جورجيا (UG)',
      'auto_trans_1142': 'إيليا ستيت (Ilia State)',
      'auto_trans_1143': 'جامعة تبليسي الحكومية (TSU)',
      'auto_trans_1144': 'شقة',
      'auto_trans_1145': 'بمفردك',
      'auto_trans_1146': 'شقة',
      'auto_trans_1147': 'شريك',
      'auto_trans_1148': 'مشترك',
      'auto_trans_1149': 'غرفة في شقة',
      'auto_trans_1150': 'غرفة في شقة',
      'auto_trans_1151': 'شريك',
      'auto_trans_1152': 'غرفة في شقة',
      'auto_trans_1153': 'مشترك',
      'auto_trans_1154': 'سابورتالو',
      'auto_trans_1155': 'حمامات',
      'auto_trans_1156': 'الكل',
      'auto_trans_1157': 'وقت مفتوح',
      'auto_trans_1158': 'مشياً',
      'auto_trans_1159': '(d+)s*دقيقة',
      'auto_trans_1160': 'طالب أبشر',
      'auto_trans_1161': 'جورجيا - تبليسي',
      'auto_trans_1162': 'أخبار جورجيا 📰',
      'auto_trans_1163': 'إعلان 📢',
      'auto_trans_1164': 'الآن',
      'auto_trans_1165': '🎓 اختر الجامعات القريبة',
      'auto_trans_1166': '💰 السعر بنفسك',
      'auto_trans_1167': '🏘️ الحي السكني',
      'auto_trans_1168': 'سابورتالو (Saburtalo)',
      'auto_trans_1169': 'فاكي (Vake)',
      'auto_trans_1170': 'ديدوبي (Didube)',
      'auto_trans_1171': '🤝 نوع السكن',
      'auto_trans_1172': '🛏️ الغرف',
      'auto_trans_1173': '🛁 الحمامات',
      'auto_trans_1174': '1 حمام',
      'auto_trans_1175': '2 حمام',
      'auto_trans_1176': '3 حمامات فأكثر',
      'auto_trans_1177': 'انتقال فوري ⚡',
      'auto_trans_1178': 'ميعاد',
      'auto_trans_1179': 'تاريخ',
      'auto_trans_1180': 'سبتمبر',
      'auto_trans_1181': 'انقر لمعاينة الصور وحجز الشقة >>',
      'auto_trans_1182': 'زائر كريم',
      'auto_trans_1183': 'تصفح عام (ضيف)',
      'auto_trans_1184': 'الآن',
      'auto_trans_1185': 'الآن',
      'auto_trans_1186': 'إغلاق',
      'auto_trans_1187': 'الإشعارات والتنبيهات 🔔',
      'auto_trans_1188': 'تحديث الإشعارات',
      'auto_trans_1189': 'لا توجد تنبيهات عاجلة حالياً 🔕',
      'auto_trans_1190': 'التنبيهات تتم إزالتها تلقائياً بعد مرور 48 ساعة',
      'auto_trans_1191': 'الآن',
      'auto_trans_1192': 'الكل',
      'auto_trans_1193': 'الكل',
      'auto_trans_1194': 'عروض خاصة 🔥',
      'auto_trans_1195': 'قريب من التبليسي الطبية',
      'auto_trans_1196': 'ستوديو منفرد',
      'auto_trans_1197': 'غرف مشتركة',
      'auto_trans_1198': 'الكل',
      'auto_trans_1199': 'عروض',
      'auto_trans_1200': 'عروض السكن الطلابي الحصرية 🏢',
      'auto_trans_1201': 'لا توجد شقق تطابق هذا الفلتر حالياً',
      'auto_trans_1202': 'مفروشة ومجهزة ✨',
      'auto_trans_1203': '🇪🇬 العربية (Arabic)',
      'auto_trans_1204': '🇬🇧 English (الإنجليزي)',
      'auto_trans_1205': 'جامعة تبليسي الطبية (TSMU)',
      'auto_trans_1206': 'جامعة تبليسي الطبية (TSMU)',
      'auto_trans_1207': 'جامعة تبليسي الطبية (TSMU)',
      'auto_trans_1208': 'جامعة تبليسي الطبية (TSMU)',
      'auto_trans_1209': 'تصفح عام (ضيف)',
      'auto_trans_1210': 'زائر كريم',
      'auto_trans_1211': 'زائر',
      'auto_trans_1212': 'تصفح عام (ضيف)',
      'auto_trans_1213': 'زائر كريم',
      'auto_trans_1214': 'زائر',
      'auto_trans_1215': 'تسجيل الدخول',
      'auto_trans_1216': 'طلب شريك سكن (Find Roommate):\n',
      'auto_trans_1217': 'لا يوجد',
      'auto_trans_1218': 'جاري إرسال طلب السكن... ⏳',
      'auto_trans_1219': 'طالب أبشر',
      'auto_trans_1220': 'جامعة في جورجيا',
      'auto_trans_1221': 'حجز سكن (شقة بمفردك)',
      'auto_trans_1222': 'جاري الاتصال بخدمة العملاء... ⏳',
      'auto_trans_1223': 'مرحباً، أريد مساعدة خدمة العملاء في حجز سكن بمفردي (Rent Flat - Alone).',
      'auto_trans_1224': 'طالب أبشر',
      'auto_trans_1225': 'جامعة في جورجيا',
      'auto_trans_1226': 'تواصل مباشر لحجز سكن',
      'auto_trans_1227': 'أبشر',
      'auto_trans_1228': 'جميع الشقق المتاحة',
      'auto_trans_1229': 'قائمة بكافة الشقق السكنية المتاحة للطلاب مع كافة التفاصيل والأسعار.',
      'auto_trans_1230': 'شقق تناسب شخص بمفرده',
      'auto_trans_1231': 'قائمة الشقق والاستوديوهات المخصصة والمناسبة لسكن طالب واحد فقط.',
      'auto_trans_1232': 'نموذج البحث عن شريك',
      'auto_trans_1233': 'قم بتعبئة بياناتك ليقوم فريق أبشر بمطابقتك مع الشريك الأنسب:',
      'auto_trans_1234': 'الاسم الكامل',
      'auto_trans_1235': 'مطلوب',
      'auto_trans_1236': 'الجنسية',
      'auto_trans_1237': 'مطلوب',
      'auto_trans_1238': 'الجامعة',
      'auto_trans_1239': 'التخصص الدراسي',
      'auto_trans_1240': 'مطلوب',
      'auto_trans_1241': 'رقم الواتساب',
      'auto_trans_1242': 'مطلوب',
      'auto_trans_1243': 'متى تريد الانتقال؟',
      'auto_trans_1244': 'مطلوب',
      'auto_trans_1245': 'ملاحظات إضافية',
      'auto_trans_1246': 'إرسال إلى خدمة العملاء',
      'auto_trans_1247': 'جامعة تبليسي الطبية (TSMU)',
      'auto_trans_1248': 'جامعة تبليسي الطبية (TSMU)',
      'auto_trans_1249': 'زائر',
      'auto_trans_1250': 'تسجيل الدخول',
      'auto_trans_1251': 'جاري إرسال طلب الشريك... ⏳',
      'auto_trans_1252': 'طالب أبشر',
      'auto_trans_1253': 'جامعة في جورجيا',
      'auto_trans_1254': 'بحث عن شريك سكن (Roommate)',
      'auto_trans_1255': 'تجميع الطلاب في شقة مشتركة 🤝',
      'auto_trans_1256': 'الاسم الكامل',
      'auto_trans_1257': 'مطلوب',
      'auto_trans_1258': 'الجامعة',
      'auto_trans_1259': 'التخصص',
      'auto_trans_1260': 'مطلوب',
      'auto_trans_1261': 'رقم هاتف التواصل (واتساب)',
      'auto_trans_1262': 'مطلوب',
      'auto_trans_1263': 'الميزانية الشهرية المقدرة للشخص (بالدولار USD)',
      'auto_trans_1264': 'مطلوب',
      'auto_trans_1265': 'ملاحظات إضافية (مثال: تفضيل التدخين، الهدوء، إلخ)',
      'auto_trans_1266': 'إرسال طلب التجميع لفريق الدعم',
      'auto_trans_1267': 'فني كهربائي',
      'auto_trans_1268': 'صيانة كافة الأعطال والتوصيلات الكهربائية',
      'auto_trans_1269': 'فني سباكة',
      'auto_trans_1270': 'إصلاح تسريبات المياه والصيانة الصحية',
      'auto_trans_1271': 'استخراج إقامة طلابية',
      'auto_trans_1272': 'تجهيز أوراق الإقامة لأول مرة أو التجديد',
      'auto_trans_1273': 'تسجيل العنوان القانوني',
      'auto_trans_1274': 'إصدار وثيقة العنوان المعتمدة في جورجيا',
      'auto_trans_1275': 'التسجيل والنقل الجامعي',
      'auto_trans_1276': 'إجراءات القبول وتحويل الساعات بين الجامعات',
      'auto_trans_1277': 'زائر',
      'auto_trans_1278': 'تسجيل الدخول',
      'auto_trans_1279': 'لم يتم التحديد',
      'auto_trans_1280': 'تنظيف',
      'auto_trans_1281': 'إلغاء',
      'auto_trans_1282': 'لم يُحدد',
      'auto_trans_1283': 'نعم ✔️',
      'auto_trans_1284': 'لا',
      'auto_trans_1285': 'بدون ملاحظات إضافية',
      'auto_trans_1286': 'خصم من نقاط المحفظة 🪙',
      'auto_trans_1287': 'الدفع نقداً 💵',
      'auto_trans_1288': 'فشل الخصم من النقاط',
      'auto_trans_1289': 'طالب أبشر',
      'auto_trans_1290': 'جامعة في جورجيا',
      'auto_trans_1291': 'إضافة',
      'auto_trans_1292': 'طالب تجريبي (أبشر)',
      'auto_trans_1293': 'جامعة تبليسي الطبية (TSMU)',
      'auto_trans_1294': 'تم تسجيل الحساب بنجاح',
      'auto_trans_1295': 'شقة طلابية ممتازة',
      'auto_trans_1296': 'شقة سكنية',
      'auto_trans_1297': 'سعر مميز',
      'auto_trans_1298': 'تبليسي',
      'auto_trans_1299': 'موقع ممتاز',
      'auto_trans_1300': '3 غرف',
      'auto_trans_1301': 'شقة',
      'auto_trans_1302': 'فوري',
      'auto_trans_1303': 'انتقال فوري ⚡',
      'auto_trans_1304': 'شقة طلابية فاخرة - شارع بيكيني (Pekini)',
      'auto_trans_1305': '450 دولار / شهر',
      'auto_trans_1306': 'تبليسي - საბურთალო (سابورتالو)',
      'auto_trans_1307': 'قريبة جداً من التبليسي الطبية TSMU (مشياً)',
      'auto_trans_1308': '3 غرف',
      'auto_trans_1309': 'شقة',
      'auto_trans_1310': 'فوري',
      'auto_trans_1311': 'انتقال فوري ⚡',
      'auto_trans_1312': '3 غرف واسعة',
      'auto_trans_1313': 'تدفئة مركزية دافئة',
      'auto_trans_1314': 'بلكونة بإطلالة مفتوحة',
      'auto_trans_1315': 'إنترنت ألياف ضوئية سريع',
      'auto_trans_1316': 'مفروشة بالكامل',
      'auto_trans_1317': 'جامعة تبليسي الطبية (TSMU)',
      'auto_trans_1318': 'شقة ممتازة للطلاب في قلب تبليسي بالقرب من محطة مترو التكنيكال. مجهزة بالكامل بالفرش والأجهزة الكهربائية مع إطلالة رائعة من البلكونة وتدفئة مركزية ممتازة للشتاء. الدفع يتم نقداً عند الاستلام.',
      'auto_trans_1319': 'ستوديو مودرن - بالقرب من جامعة جورجيا (UG)',
      'auto_trans_1320': '380 دولار / شهر',
      'auto_trans_1321': 'تبليسي - شارع كوستافا',
      'auto_trans_1322': 'جامعة جورجيا UG وستيت UT',
      'auto_trans_1323': '1 غرفة',
      'auto_trans_1324': 'شقة',
      'auto_trans_1325': 'فوري',
      'auto_trans_1326': 'انتقال فوري ⚡',
      'auto_trans_1327': 'ستوديو منفرد هادئ',
      'auto_trans_1328': 'تكييف وتدفئة',
      'auto_trans_1329': 'أمن على مدار 24 ساعة',
      'auto_trans_1330': 'قريب من السوبرماركت',
      'auto_trans_1331': 'ستوديو مثالي للطالب المنفرد الباحث عن الهدوء والتركيز في الدراسة. يبعد دقائق مشياً عن حرم جامعة جورجيا. أثاث حديث ومطبخ مجهز بالكامل.',
      'auto_trans_1332': 'شقة مشتركة لـ 3 طلاب - إطلالة بنورامية',
      'auto_trans_1333': '550 دولار (أو 180 دولار للشخص)',
      'auto_trans_1334': 'تبليسي - فاكي (Vake)',
      'auto_trans_1335': 'قريبة من جامعة إيليا والطبية',
      'auto_trans_1336': '3 غرف',
      'auto_trans_1337': 'غرفة في شقة',
      'auto_trans_1338': 'فوري',
      'auto_trans_1339': 'انتقال فوري ⚡',
      'auto_trans_1340': 'غرف منفصلة ومريحة',
      'auto_trans_1341': 'صالة كبيرة للمذاكرة المشتركة',
      'auto_trans_1342': 'بلكونة واسعة جداً',
      'auto_trans_1343': 'مصعد يعمل 24/7',
      'auto_trans_1344': 'جامعة إيليا الحكومية (Ilia)',
      'auto_trans_1345': 'فرصة ممتازة لثلاثة أصدقاء طلاب أو لتجميع الطلاب. مساحة واسعة وتوزيع ممتاز للغرف يضمن الخصوصية لكل طالب.',
      'auto_trans_1346': 'جامعة تبليسي الطبية (TSMU)',
      'auto_trans_1347': 'جامعة جورجيا (UG)',
      'auto_trans_1348': 'جامعة إيليا الحكومية (Ilia)',
      'auto_trans_1349': 'جامعة تبليسي الحكومية (TSU)',
      'auto_trans_1350': 'سابورتالو (Saburtalo)',
      'auto_trans_1351': 'فاكي (Vake)',
      'auto_trans_1352': 'ديدوبي (Didube)',
      'auto_trans_1353': 'متاتسميندا (Mtatsminda)',
      'auto_trans_1354': 'إساني (Isani)',
      'auto_trans_1355': 'جلَداني (Gldani)',
      'auto_trans_1356': 'الآن',
      'auto_trans_1357': '💧 انقطاع المياه غداً الأحد في سابورتالو',
      'auto_trans_1358': 'تعلن شركة المياه الوطنية عن قطع مؤقت لإمدادات المياه غداً الأحد من الساعة 10:00 صباحاً وحتى الساعة 04:00 عصراً لإجراء أعمال الصيانة السنوية لخطوط الإمداد المغذية للمنطقة.',
      'auto_trans_1359': 'منذ ساعة',
      'auto_trans_1360': '🕌 تعديل موعد صلاة الجمعة في مسجد تبليسي',
      'auto_trans_1361': 'تقرر بدء الخطبة الأولى لصلاة الجمعة المباركة في مسجد تبليسي المركزي في تمام الساعة 01:30 ظهراً بدلاً من الساعة 01:00 ظهراً لتسهيل انضمام المصلين من الجامعات المختلفة.',
      'auto_trans_1362': 'منذ 3 ساعات',
      'auto_trans_1363': '⚡ قطع الكهرباء المجدول يوم الثلاثاء القادم',
      'auto_trans_1364': 'فصل مبرمج للتيار الكهربائي عن أجزاء من حي ديدوبي Didube يوم الثلاثاء القادم من الساعة 09:00 صباحاً إلى الساعة 11:00 صباحاً لتوصيل محولات شبكية جديدة وتحسين استقرار الطاقة.',
      'auto_trans_1365': 'أمس',
      'auto_trans_1366': 'الآن',
      'auto_trans_1367': '💧 تنبيه انقطاع المياه في سابورتالو',
      'auto_trans_1368': 'نسترعي انتباه الطلاب الكرام في سابورتالو بأنه سيتم قطع المياه غداً الأحد من الساعة 10:00 صباحاً وحتى الساعة 04:00 عصراً.',
      'auto_trans_1369': 'منذ ساعة',
      'auto_trans_1370': '🕌 صلاة الجمعة في مسجد تبليسي',
      'auto_trans_1371': 'تقرر بدء خطبة صلاة الجمعة المباركة في تمام الساعة 01:30 ظهراً لتسهيل انضمام الطلاب من مختلف الجامعات.',
      'auto_trans_1372': 'منذ 3 ساعات',
      'auto_trans_1373': 'خدمة طلابية',
      'auto_trans_1374': 'فني كهربائي',
      'auto_trans_1375': 'صيانة كافة الأعطال والتوصيلات الكهربائية',
      'auto_trans_1376': 'فني سباكة',
      'auto_trans_1377': 'إصلاح تسريبات المياه والصيانة الصحية',
      'auto_trans_1378': 'استخراج إقامة طلابية',
      'auto_trans_1379': 'تجهيز أوراق الإقامة لأول مرة أو التجديد',
      'auto_trans_1380': 'تسجيل العنوان القانوني',
      'auto_trans_1381': 'إصدار وثيقة العنوان المعتمدة في جورجيا',
      'auto_trans_1382': 'التسجيل والنقل الجامعي',
      'auto_trans_1383': 'إجراءات القبول وتحويل الساعات بين الجامعات',
      'auto_trans_1384': 'تم إرسال الطلب وحفظه مؤقتاً في التطبيق',
      'auto_trans_1385': 'الآن',
      'auto_trans_1386': 'حدث خطأ في الاتصال بالخادم',
      'auto_trans_1387': 'معاينة الفيديو (YouTube / Drive) متاحة على الويب'
    },
    'en': {
      'app_title': 'ABSHER Georgia',
      'welcome': 'Welcome,',
      'home': 'Home',
      'services': 'Services',
      'chat': 'Chat',
      'offers': 'Offers',
      'profile': 'Profile',
      'change_lang': 'Change App Language',
      'lang_desc': 'English / Arabic / Georgian',
      'logout': 'Logout from Account',
      'guest_logout': 'Exit to Login Screen',
      'guest_mode': 'You are currently browsing as a guest!',
      'roommate_match': 'Roommate Matchmaking 🤝',
      'roommate_desc': 'Register your details and support will match you with compatible roommates.',
      'quick_services': 'Quick Student Services ⚡',
      'view_all': 'View All',
      'browse_apts': 'Browse Available Student Apartments 🏠',
      'no_commission': 'Direct & Furnished Student Offers 🔥',
      'cash_payment': 'Safe Cash Payment upon Delivery',
      'my_bookings': 'My Bookings & Requests',
      'payment_method': 'Payment Method in ABSHER',
      'contact_support': 'Direct Contact with Support',
      'about_app': 'About ABSHER App',
      'splash_subtitle': 'ABSHER - Your Premier Student Companion in Georgia',
      'skip_to_start': 'Skip to Start >>',
      'login_fail': 'Login failed. Check your credentials.',
      'login_welcome': 'Welcome to ABSHER',
      'login_subtitle': 'Log in to access student housing and services in Georgia',
      'email_or_phone': 'Email or Phone Number',
      'please_enter_email': 'Please enter email or phone',
      'password': 'Password',
      'please_enter_password': 'Please enter password',
      'contact_support_pw': 'Contact support on Instagram @absher_georgia to recover account',
      'forgot_pw': 'Forgot Password?',
      'login_btn': 'Log In',
      'enter_as_guest': 'Enter as Guest & Explore',
      'no_account_yet': 'Don\'t have a student account yet?',
      'create_new_account': 'Create New Account',
      'guest_name': 'Respected Guest',
      'guest_uni': 'General Browsing (Guest)',
      'other_uni_manual': 'Other (Manual Entry)',
      'register_fail': 'Account creation failed. Check details.',
      'create_account_title': 'Create New Student Account',
      'create_account_subtitle': 'Join ABSHER family and benefit from all our services in Georgia',
      'full_name': 'Full Name',
      'required_field': 'Required',
      'email': 'Email',
      'invalid_email': 'Invalid Email',
      'phone_example': 'Phone Number (e.g., +995555123456)',
      'georgia_uni': 'University in Georgia',
      'uni_and_district': 'University Name and District',
      'please_enter_uni_dist': 'Please enter university and district',
      'pw_min_6': 'At least 6 characters',
      'create_account_btn': 'Create Account Now',
      'already_have_account': 'Already have an account?',
      'all_flats': 'All Flats',
      'flat_alone': 'Flat Alone',
      'with_roommate': 'With Roommate',
      'all_districts': 'All Districts',
      'all': 'All',
      'select_rooms': 'Select Rooms...',
      'one_room': '1 Room',
      'two_rooms': '2 Rooms',
      'three_plus_rooms': '3+ Rooms',
      'filter_flats': 'Filter Flats',
      'rental_type': 'Rental Type:',
      'district': 'District:',
      'bedrooms': 'Bedrooms:',
      'bathrooms': 'Bathrooms:',
      'distance_uni': 'Distance to Uni (walking):',
      '10_mins': '10 mins',
      '20_mins': '20 mins',
      '30_mins': '30 mins',
      'apply_filter': 'Apply Filter',
      'cancel': 'Cancel',
      'select_nearby_unis': '🎓 Select Nearby Universities',
      'confirm_selection': 'Confirm Selection',
      'search_flats': 'Search Flats...',
      'no_results': 'No results matching your search',
      'details': 'Details',
      'book_now': 'Book Now',
      'welcome_user': 'Welcome,',
      'wallet_points': 'Wallet & Points',
      'current_points_balance': 'Current Points Balance',
      'points_usage_desc': 'You can use points to pay for services',
      'transaction_history': 'Transaction History',
      'no_previous_transactions': 'No previous transactions',
      'default_student_name': 'Respected Student',
      'default_student_uni': 'University of Georgia',
      'create_account_now': 'Create a student account now to benefit from all offers and request roommate matching.',
      'login_or_register': 'Login / Register',
      'booking_status_subtitle': 'Track your flat status or roommate request',
      'wallet_subtitle': 'Track balance and pay with points',
      'please_login_wallet': 'Please login first to use wallet',
      'support_subtitle': 'Instagram @absher_georgia or by phone',
      'about_subtitle': 'Version 1.0.0 - ABSHER in Georgia',
      'clicked_on': 'Clicked on:',
      'available_options': 'Available Options',
      'furnished_equipped': 'Furnished & Equipped ✔️',
      'no_matching_flats': 'No matching flats currently in this list.',
      'go_back': 'Go Back',
      'immediate_move_in': 'Immediate Move-in ⚡',
      'click_to_view_images': 'Click to view images and book >>',
      'apartment_details': 'Apartment Details',
      'images_count': 'Images',
      'apartment_number': 'Apartment #',
      'proximity_label': 'Proximity:',
      'close_to_unis': 'Close to main universities',
      'roommate_reqs_title': 'Rent with Roommate (Requirements):',
      'roommate_reqs': '👤 Roommate Requirements:',
      'roommate_facilities': '🏠 Available Space & Facilities:',
      'features_and_facilities': 'Features & Facilities',
      'great_features': 'Great features',
      'apartment_description': 'Apartment Description',
      'guest_alert_title': 'Alert 🔒',
      'guest_alert_body_booking': 'Sorry, you cannot request a booking without logging in.',
      'guest_alert_body_roommate': 'Sorry, you must login to send a roommate request!',
      'choose_housing_method': 'Choose your housing method',
      'housing_method_desc': 'You can book a flat alone or fill out a roommate form.',
      'browse_flats': 'Browse Flats',
      'browse_flats_desc': 'View available flats with all images and prices.',
      'all_available_flats': 'All Available Flats',
      'all_available_flats_desc': 'List of all available flats for students with details and prices.',
      'flat_room_choice': 'Choose a room in a flat',
      'flat_room_desc': 'Show flats and studios suitable for one person.',
      'flats_for_one': 'Flats for one person',
      'flats_for_one_desc': 'Flats and studios dedicated to single students.',
      'roommate_form_title': 'Roommate Request Form',
      'roommate_form_desc': 'Fill out your info and we will match you with the best roommate.',
      'full_name_label': 'Full Name',
      'nationality_label': 'Nationality',
      'gender_label': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'males_only': 'Males Only',
      'females_only': 'Females Only',
      'university_label': 'University',
      'major_label': 'Major',
      'major_study_label': 'Major of Study',
      'whatsapp_number': 'WhatsApp Number',
      'whatsapp_contact_number': 'Contact WhatsApp Number',
      'when_move_in': 'When do you want to move?',
      'move_in_date_label': 'Required Move-in Date',
      'immediate_move': 'Immediate / ASAP',
      'this_month_move': 'During this month',
      'next_semester_move': 'At the start of the next semester',
      'choose_date': 'Choose a Date',
      'additional_notes': 'Additional Notes',
      'additional_notes_hint': 'Additional Notes (e.g., smoking, quiet, etc)',
      'send_to_customer_service': 'Send to Customer Service',
      'send_roommate_request': 'Send Match Request to Support',
      'roommate_match_title': 'Student Flat Matching 🤝',
      'roommate_match_card_title': 'Find a compatible roommate!',
      'roommate_match_card_desc': 'Register your info and budget, and we will match you with students from your uni.',
      'your_info_and_prefs': 'Your Info & Housing Prefs',
      'monthly_budget_usd': 'Estimated Monthly Budget per Person (USD)',
      'housing_type_req': 'Required Housing Type',
      'guest_alert_body_services': 'Sorry, you must login to request services and instant maintenance!',
      'service_form_title': 'Service Request Form',
      'service_form_desc': 'Choose a service and fill in the request details:',
      'requested_service': 'Requested Service',
      'whatsapp_contact_short': 'WhatsApp Contact Number',
      'detailed_address': 'Detailed Address',
      'best_time_to_execute': 'Best Execution Time (from Calendar)',
      'attach_image_optional': 'Attach Image (Optional)',
      'image_attached_success': 'Image Attached ✔️',
      'cleaning_details_title': 'Set Home Area & Estimated Price (3-4 GEL per meter):',
      'number_of_rooms': 'Number of Rooms',
      'area_in_meters': 'Area (meters)',
      'estimated_cost': 'Estimated Cost:',
      'currency_gel': 'GEL',
      'notes_details_hint': 'Write your specific details and notes here...',
      'notes_and_details': 'Notes & Order Details',
      'promo_code': 'Promo Code',
      'use_wallet_points': 'Use wallet points to pay',
      'submit_form_confirm': 'Submit Form & Confirm Order',
      'all_student_services': 'All ABSHER Student Services 🛠️',
      'instant_tag': 'Instant 📝',
      'request_service_button': 'Request Service 🛠️',
      'welcome_chat_msg': 'Welcome to ABSHER live support 🌟! How can we help you today with housing or services in Georgia?',
      'rate_customer_service': 'Rate Customer Service',
      'rate_customer_service_desc': 'How satisfied are you with the speed and quality of ABSHER technical support? (Admin visibility only)',
      'additional_comments_hint': 'Additional notes or comments...',
      'submit_rating': 'Submit Rating',
      'rating_success_msg': 'Your rating has been submitted to ABSHER management and saved successfully. Thank you!',
      'attach_link': 'Attach Link 🔗',
      'enter_or_paste_link': 'Enter or paste any link to share in the chat:',
      'url_label': 'URL',
      'send_now': 'Send Now',
      'attach_youtube_drive': 'Attach YouTube or Drive Video 🎥',
      'enter_youtube_drive_link': 'Enter or paste a video link from YouTube or Google Drive:',
      'video_url_label': 'Video URL',
      'uploading_file_loading': 'Uploading and sending file... ⏳',
      'file_upload_success': 'File uploaded and sent successfully! ✅',
      'file_upload_fail': 'Sorry, failed to upload file to the server ❌',
      'attach_media_chat': 'Attach media to chat 📎',
      'choose_image_gallery': '📷 Choose image from gallery',
      'choose_video_gallery': '🎥 Choose video from gallery',
      'manual_link_input': '🔗 Manual file link input (external site)',
      'preview_video_attachment': '🎥 Preview Attached Video',
      'preview_image_attachment': '📷 Preview Attached Image',
      'video_player_active': 'Video player active 🎥',
      'absher_support_chat_title': 'ABSHER Management - Support & Chat',
      'rate_button': 'Rate',
      'direct_call_snackbar': 'Direct phone call or via WhatsApp +995555123456',
      'reply_to_message_selected': 'Message selected to reply 💬',
      'you': 'You',
      'tech_support': 'Tech Support',
      'click_to_play_video': 'Click to play video',
      'reply_to_yourself': 'Reply to yourself',
      'reply_to_support': 'Reply to customer service',
      'attach_image_tooltip': 'Attach Image',
      'attach_video_tooltip': 'Attach Video',
      'attach_link_tooltip': 'Attach Link',
      'type_message_hint': 'Type your message for management here...',
      'sending_service_request': 'Sending service request... ⏳',
      'error_sending_service': 'Error sending service request:',
      'auto_trans_1000': 'Absher Georgia',
      'auto_trans_1001': '12:00 PM',
      'auto_trans_1002': 'Guest',
      'auto_trans_1003': 'Important Notice',
      'auto_trans_1004': 'Sorry, you must log in or create a student account first to book apartments and student housing!',
      'auto_trans_1005': 'Cancel',
      'auto_trans_1006': 'Login',
      'auto_trans_1007': 'You are about to request a viewing for: ',
      'auto_trans_1008': '. Payment is in cash upon arrival.',
      'auto_trans_1009': 'Contact Phone Number (WhatsApp)',
      'auto_trans_1010': 'Viewing Day',
      'auto_trans_1011': 'Suitable Time',
      'auto_trans_1012': 'Additional Notes (e.g. specific meeting point)',
      'auto_trans_1013': 'Note: Any change or modification in the appointment is easily and directly done through chat with customer service.',
      'auto_trans_1014': 'Sending booking request... ⏳',
      'auto_trans_1015': 'None',
      'auto_trans_1016': '💡 Note: The student wants to view the apartment at this time, and any change in time is coordinated via this chat.',
      'auto_trans_1017': 'Absher Student',
      'auto_trans_1018': 'University in Georgia',
      'auto_trans_1019': 'Confirm Request and Go to Instant Chat 💬',
      'auto_trans_1020': 'Tbilisi, Georgia',
      'auto_trans_1021': 'Roommate',
      'auto_trans_1022': 'Now',
      'auto_trans_1023': 'Now',
      'auto_trans_1024': 'Now',
      'auto_trans_1025': 'Now',
      'auto_trans_1026': 'Student',
      'auto_trans_1027': 'University in Georgia',
      'auto_trans_1028': 'Absher Student',
      'auto_trans_1029': 'University in Georgia',
      'auto_trans_1030': 'Excellent rating with no additional notes',
      'auto_trans_1031': 'Now',
      'auto_trans_1032': 'Student',
      'auto_trans_1033': 'University in Georgia',
      'auto_trans_1034': 'Cancel',
      'auto_trans_1035': 'Cancel',
      'auto_trans_1036': '🎥 Video attached by student',
      'auto_trans_1037': '📷 Image attached by student',
      'auto_trans_1038': 'Studio',
      'auto_trans_1039': 'Single',
      'auto_trans_1040': '1 Room',
      'auto_trans_1041': 'Private',
      'auto_trans_1042': 'Shared for 3',
      'auto_trans_1043': 'Absher',
      'auto_trans_1044': 'Date',
      'auto_trans_1045': 'Date',
      'auto_trans_1046': 'September',
      'auto_trans_1047': 'Latest Georgia News 📰',
      'auto_trans_1048': 'Update News',
      'auto_trans_1049': 'No news currently 📰',
      'auto_trans_1050': 'Now',
      'auto_trans_1051': 'School Season Offers 🎓',
      'auto_trans_1052': 'Book your student housing now easily and safely!',
      'auto_trans_1053': 'Safe cash payment directly upon receiving your apartment key in Tbilisi.',
      'auto_trans_1054': 'Exclusive Offers 🔥',
      'auto_trans_1055': 'Economical Shared Housing 🤝',
      'auto_trans_1056': 'Grouping students in apartments near universities',
      'auto_trans_1057': 'Save half the rent and register your name for support to match you with compatible peers.',
      'auto_trans_1058': 'Save 50% 💰',
      'auto_trans_1059': 'Airport Reception and University Transfer 🚖',
      'auto_trans_1060': 'Recently arrived in Tbilisi? We welcome you!',
      'auto_trans_1061': 'Comfortable cars and representatives to assist you on your first step and deliver you to your door.',
      'auto_trans_1062': '24/7 Service ⚡',
      'auto_trans_1063': 'Student Residencies and Legal Registration 🛂',
      'auto_trans_1064': 'Clearing all your university and legal papers',
      'auto_trans_1065': 'A specialized team to ensure the safety of your legal status and residency in Georgia easily.',
      'auto_trans_1066': 'Guaranteed and Certified 📜',
      'auto_trans_1067': 'Luxury Student Apartment - Pekini Street',
      'auto_trans_1068': '450 USD / Month',
      'auto_trans_1069': 'Saburtalo',
      'auto_trans_1070': 'TSMU (10 mins walk) | UG (20 mins)',
      'auto_trans_1071': 'Apartment alone',
      'auto_trans_1072': '3 Individuals (Full Apartment)',
      'auto_trans_1073': 'Apartment alone',
      'auto_trans_1074': '2 Bathrooms',
      'auto_trans_1075': '3 Spacious Rooms',
      'auto_trans_1076': 'Warm Central Heating',
      'auto_trans_1077': 'Balcony with open view',
      'auto_trans_1078': 'Fast Fiber Optic Internet',
      'auto_trans_1079': 'Fully Furnished',
      'auto_trans_1080': 'Excellent student apartment in the heart of Tbilisi near the Technical metro station. Fully equipped with furniture and appliances, with a wonderful view from the balcony and excellent central heating for winter. Payment is cash on delivery.',
      'auto_trans_1081': 'Modern Studio - Near UG',
      'auto_trans_1082': '380 USD / Month',
      'auto_trans_1083': 'Vake',
      'auto_trans_1084': 'UG (10 mins walk) | Ilia State (15 mins)',
      'auto_trans_1085': 'Apartment alone',
      'auto_trans_1086': '1 Individual (Single Studio)',
      'auto_trans_1087': 'Apartment alone',
      'auto_trans_1088': '1 Bathroom',
      'auto_trans_1089': 'Quiet Single Studio',
      'auto_trans_1090': 'AC & Heating',
      'auto_trans_1091': '24-hour Security',
      'auto_trans_1092': 'Close to Supermarket',
      'auto_trans_1093': 'Perfect studio for a single student looking for peace and focus on studies. Minutes walk from UG campus. Modern furniture and fully equipped kitchen.',
      'auto_trans_1094': 'Shared Apartment for 3 Students - Panoramic View',
      'auto_trans_1095': '550 USD (or 180 USD per person)',
      'auto_trans_1096': 'Saburtalo',
      'auto_trans_1097': 'Ilia State (10 mins) | TSU (20 mins)',
      'auto_trans_1098': 'Rent with Roommate',
      'auto_trans_1099': '3 Individuals (Shared Apartment)',
      'auto_trans_1100': 'Non-smoker, quiet and respectful student, maintains general cleanliness and calm',
      'auto_trans_1101': 'Private furnished bedroom, shared bathroom and kitchen, balcony (spacious)',
      'auto_trans_1102': 'Rent with Roommate',
      'auto_trans_1103': '2 Bathrooms',
      'auto_trans_1104': 'Separate and comfortable rooms',
      'auto_trans_1105': 'Large hall for joint study',
      'auto_trans_1106': 'Very large balcony',
      'auto_trans_1107': 'Elevator works 24/7',
      'auto_trans_1108': 'Excellent opportunity for three student friends or grouping students. Spacious area and excellent room distribution ensures privacy for each student.',
      'auto_trans_1109': 'Luxury Independent Studio - Aghmashenebeli Street',
      'auto_trans_1110': '400 USD / Month',
      'auto_trans_1111': 'Didube',
      'auto_trans_1112': 'Walking to metro station and universities (10 mins)',
      'auto_trans_1113': 'Apartment alone',
      'auto_trans_1114': '1 Individual',
      'auto_trans_1115': 'Apartment alone',
      'auto_trans_1116': '1 Bathroom',
      'auto_trans_1117': 'Independent studio for one person',
      'auto_trans_1118': 'AC & Heating',
      'auto_trans_1119': 'Fast Internet',
      'auto_trans_1120': 'New Furniture',
      'auto_trans_1121': 'Private studio apartment for one person in an excellent location near services and transportation.',
      'auto_trans_1122': 'Apartment with Roommate - Saburtalo near Medical',
      'auto_trans_1123': '220 USD per person',
      'auto_trans_1124': 'Saburtalo',
      'auto_trans_1125': 'TSMU (5 mins walk)',
      'auto_trans_1126': 'Rent with Roommate',
      'auto_trans_1127': 'One roommate required',
      'auto_trans_1128': 'Medical or engineering student, non-smoker, maintains calm and cleanliness',
      'auto_trans_1129': 'Large private air-conditioned bedroom, shared bathroom and kitchen with only one student',
      'auto_trans_1130': 'Rent with Roommate',
      'auto_trans_1131': '1 Bathroom',
      'auto_trans_1132': '1 independent bedroom for roommate',
      'auto_trans_1133': 'Equipped kitchen',
      'auto_trans_1134': 'Quiet balcony',
      'auto_trans_1135': 'Excellent apartment for a student looking for a quiet and respectful roommate steps away from TSMU.',
      'auto_trans_1136': 'Notifications & Alerts 🔔',
      'auto_trans_1137': 'No new alerts currently 🔕',
      'auto_trans_1138': 'Now',
      'auto_trans_1139': 'All',
      'auto_trans_1140': 'TSMU',
      'auto_trans_1141': 'UG',
      'auto_trans_1142': 'Ilia State',
      'auto_trans_1143': 'TSU',
      'auto_trans_1144': 'Apartment',
      'auto_trans_1145': 'Alone',
      'auto_trans_1146': 'Apartment',
      'auto_trans_1147': 'Roommate',
      'auto_trans_1148': 'Shared',
      'auto_trans_1149': 'Room in Apartment',
      'auto_trans_1150': 'Room in Apartment',
      'auto_trans_1151': 'Roommate',
      'auto_trans_1152': 'Room in Apartment',
      'auto_trans_1153': 'Shared',
      'auto_trans_1154': 'Saburtalo',
      'auto_trans_1155': 'Bathrooms',
      'auto_trans_1156': 'All',
      'auto_trans_1157': 'Open Time',
      'auto_trans_1158': 'Walking',
      'auto_trans_1159': '(d+)s*mins',
      'auto_trans_1160': 'Absher Student',
      'auto_trans_1161': 'Georgia - Tbilisi',
      'auto_trans_1162': 'Georgia News 📰',
      'auto_trans_1163': 'Announcement 📢',
      'auto_trans_1164': 'Now',
      'auto_trans_1165': '🎓 Select nearby universities',
      'auto_trans_1166': '💰 Price yourself',
      'auto_trans_1167': '🏘️ District',
      'auto_trans_1168': 'Saburtalo',
      'auto_trans_1169': 'Vake',
      'auto_trans_1170': 'Didube',
      'auto_trans_1171': '🤝 Accommodation Type',
      'auto_trans_1172': '🛏️ Rooms',
      'auto_trans_1173': '🛁 Bathrooms',
      'auto_trans_1174': '1 Bathroom',
      'auto_trans_1175': '2 Bathrooms',
      'auto_trans_1176': '3 Bathrooms or more',
      'auto_trans_1177': 'Immediate Move-in ⚡',
      'auto_trans_1178': 'Date',
      'auto_trans_1179': 'Date',
      'auto_trans_1180': 'September',
      'auto_trans_1181': 'Click to preview photos and book apartment >>',
      'auto_trans_1182': 'Dear Guest',
      'auto_trans_1183': 'General Browsing (Guest)',
      'auto_trans_1184': 'Now',
      'auto_trans_1185': 'Now',
      'auto_trans_1186': 'Close',
      'auto_trans_1187': 'Notifications & Alerts 🔔',
      'auto_trans_1188': 'Update Notifications',
      'auto_trans_1189': 'No urgent alerts currently 🔕',
      'auto_trans_1190': 'Alerts are automatically removed after 48 hours',
      'auto_trans_1191': 'Now',
      'auto_trans_1192': 'All',
      'auto_trans_1193': 'All',
      'auto_trans_1194': 'Special Offers 🔥',
      'auto_trans_1195': 'Near TSMU',
      'auto_trans_1196': 'Single Studio',
      'auto_trans_1197': 'Shared Rooms',
      'auto_trans_1198': 'All',
      'auto_trans_1199': 'Offers',
      'auto_trans_1200': 'Exclusive Student Housing Offers 🏢',
      'auto_trans_1201': 'No apartments match this filter currently',
      'auto_trans_1202': 'Furnished & Equipped ✨',
      'auto_trans_1203': '🇪🇬 Arabic',
      'auto_trans_1204': '🇬🇧 English',
      'auto_trans_1205': 'TSMU',
      'auto_trans_1206': 'TSMU',
      'auto_trans_1207': 'TSMU',
      'auto_trans_1208': 'TSMU',
      'auto_trans_1209': 'General Browsing (Guest)',
      'auto_trans_1210': 'Dear Guest',
      'auto_trans_1211': 'Guest',
      'auto_trans_1212': 'General Browsing (Guest)',
      'auto_trans_1213': 'Dear Guest',
      'auto_trans_1214': 'Guest',
      'auto_trans_1215': 'Login',
      'auto_trans_1216': 'Find Roommate Request:\n',
      'auto_trans_1217': 'None',
      'auto_trans_1218': 'Sending housing request... ⏳',
      'auto_trans_1219': 'Absher Student',
      'auto_trans_1220': 'University in Georgia',
      'auto_trans_1221': 'Book Housing (Apartment Alone)',
      'auto_trans_1222': 'Connecting to customer service... ⏳',
      'auto_trans_1223': 'Hello, I need customer service help to book a flat alone.',
      'auto_trans_1224': 'Absher Student',
      'auto_trans_1225': 'University in Georgia',
      'auto_trans_1226': 'Direct contact for housing booking',
      'auto_trans_1227': 'Absher',
      'auto_trans_1228': 'All Available Flats',
      'auto_trans_1229': 'List of all available flats for students with all details and prices.',
      'auto_trans_1230': 'Flats for one person',
      'auto_trans_1231': 'List of flats and studios dedicated to single students.',
      'auto_trans_1232': 'Roommate Request Form',
      'auto_trans_1233': 'Fill out your info and we will match you with the best roommate:',
      'auto_trans_1234': 'Full Name',
      'auto_trans_1235': 'Required',
      'auto_trans_1236': 'Nationality',
      'auto_trans_1237': 'Required',
      'auto_trans_1238': 'University',
      'auto_trans_1239': 'Major of Study',
      'auto_trans_1240': 'Required',
      'auto_trans_1241': 'WhatsApp Number',
      'auto_trans_1242': 'Required',
      'auto_trans_1243': 'When do you want to move?',
      'auto_trans_1244': 'Required',
      'auto_trans_1245': 'Additional Notes',
      'auto_trans_1246': 'Send to Customer Service',
      'auto_trans_1247': 'TSMU',
      'auto_trans_1248': 'TSMU',
      'auto_trans_1249': 'Guest',
      'auto_trans_1250': 'Login',
      'auto_trans_1251': 'Sending roommate request... ⏳',
      'auto_trans_1252': 'Absher Student',
      'auto_trans_1253': 'University in Georgia',
      'auto_trans_1254': 'Roommate Search',
      'auto_trans_1255': 'Student Flat Matching 🤝',
      'auto_trans_1256': 'Full Name',
      'auto_trans_1257': 'Required',
      'auto_trans_1258': 'University',
      'auto_trans_1259': 'Major',
      'auto_trans_1260': 'Required',
      'auto_trans_1261': 'Contact Phone Number (WhatsApp)',
      'auto_trans_1262': 'Required',
      'auto_trans_1263': 'Estimated Monthly Budget per Person (USD)',
      'auto_trans_1264': 'Required',
      'auto_trans_1265': 'Additional Notes (e.g. smoking preference, calm, etc.)',
      'auto_trans_1266': 'Send Match Request to Support',
      'auto_trans_1267': 'Electrician',
      'auto_trans_1268': 'Maintenance of all electrical faults and connections',
      'auto_trans_1269': 'Plumber',
      'auto_trans_1270': 'Repair of water leaks and plumbing',
      'auto_trans_1271': 'Student Residency Issuance',
      'auto_trans_1272': 'Preparing residency papers for the first time or renewal',
      'auto_trans_1273': 'Legal Address Registration',
      'auto_trans_1274': 'Issuance of certified address document in Georgia',
      'auto_trans_1275': 'University Registration & Transfer',
      'auto_trans_1276': 'Admission procedures and credit transfers',
      'auto_trans_1277': 'Guest',
      'auto_trans_1278': 'Login',
      'auto_trans_1279': 'Not specified',
      'auto_trans_1280': 'Cleaning',
      'auto_trans_1281': 'Cancel',
      'auto_trans_1282': 'Not specified',
      'auto_trans_1283': 'Yes ✔️',
      'auto_trans_1284': 'No',
      'auto_trans_1285': 'No additional notes',
      'auto_trans_1286': 'Deduct from wallet points 🪙',
      'auto_trans_1287': 'Pay in cash 💵',
      'auto_trans_1288': 'Failed to deduct from points',
      'auto_trans_1289': 'Absher Student',
      'auto_trans_1290': 'University in Georgia',
      'auto_trans_1291': 'Add',
      'auto_trans_1292': 'Test Student (Absher)',
      'auto_trans_1293': 'TSMU',
      'auto_trans_1294': 'Account registered successfully',
      'auto_trans_1295': 'Excellent student flat',
      'auto_trans_1296': 'Residential flat',
      'auto_trans_1297': 'Special price',
      'auto_trans_1298': 'Tbilisi',
      'auto_trans_1299': 'Excellent location',
      'auto_trans_1300': '3 Rooms',
      'auto_trans_1301': 'Apartment',
      'auto_trans_1302': 'Immediate',
      'auto_trans_1303': 'Immediate Move-in ⚡',
      'auto_trans_1304': 'Luxury Student Apartment - Pekini Street',
      'auto_trans_1305': '450 USD / Month',
      'auto_trans_1306': 'Tbilisi - Saburtalo',
      'auto_trans_1307': 'Very close to TSMU (walking)',
      'auto_trans_1308': '3 Rooms',
      'auto_trans_1309': 'Apartment',
      'auto_trans_1310': 'Immediate',
      'auto_trans_1311': 'Immediate Move-in ⚡',
      'auto_trans_1312': '3 Spacious Rooms',
      'auto_trans_1313': 'Warm Central Heating',
      'auto_trans_1314': 'Balcony with open view',
      'auto_trans_1315': 'Fast Fiber Optic Internet',
      'auto_trans_1316': 'Fully Furnished',
      'auto_trans_1317': 'TSMU',
      'auto_trans_1318': 'Excellent student apartment in the heart of Tbilisi near the Technical metro station. Fully equipped with furniture and appliances, with a wonderful view from the balcony and excellent central heating for winter. Payment is cash on delivery.',
      'auto_trans_1319': 'Modern Studio - Near UG',
      'auto_trans_1320': '380 USD / Month',
      'auto_trans_1321': 'Tbilisi - Kostava Street',
      'auto_trans_1322': 'UG and UT Universities',
      'auto_trans_1323': '1 Room',
      'auto_trans_1324': 'Apartment',
      'auto_trans_1325': 'Immediate',
      'auto_trans_1326': 'Immediate Move-in ⚡',
      'auto_trans_1327': 'Quiet Single Studio',
      'auto_trans_1328': 'AC & Heating',
      'auto_trans_1329': '24-hour Security',
      'auto_trans_1330': 'Close to Supermarket',
      'auto_trans_1331': 'Perfect studio for a single student looking for peace and focus on studies. Minutes walk from UG campus. Modern furniture and fully equipped kitchen.',
      'auto_trans_1332': 'Shared Apartment for 3 Students - Panoramic View',
      'auto_trans_1333': '550 USD (or 180 USD per person)',
      'auto_trans_1334': 'Tbilisi - Vake',
      'auto_trans_1335': 'Close to Ilia and Medical Universities',
      'auto_trans_1336': '3 Rooms',
      'auto_trans_1337': 'Room in Apartment',
      'auto_trans_1338': 'Immediate',
      'auto_trans_1339': 'Immediate Move-in ⚡',
      'auto_trans_1340': 'Separate and comfortable rooms',
      'auto_trans_1341': 'Large hall for joint study',
      'auto_trans_1342': 'Very large balcony',
      'auto_trans_1343': 'Elevator works 24/7',
      'auto_trans_1344': 'Ilia State University',
      'auto_trans_1345': 'Excellent opportunity for three student friends or grouping students. Spacious area and excellent room distribution ensures privacy for each student.',
      'auto_trans_1346': 'TSMU',
      'auto_trans_1347': 'UG',
      'auto_trans_1348': 'Ilia State University',
      'auto_trans_1349': 'TSU',
      'auto_trans_1350': 'Saburtalo',
      'auto_trans_1351': 'Vake',
      'auto_trans_1352': 'Didube',
      'auto_trans_1353': 'Mtatsminda',
      'auto_trans_1354': 'Isani',
      'auto_trans_1355': 'Gldani',
      'auto_trans_1356': 'Now',
      'auto_trans_1357': '💧 Water Cutoff Tomorrow Sunday in Saburtalo',
      'auto_trans_1358': 'National Water Company announces temporary water cutoff tomorrow Sunday from 10 AM to 4 PM for annual maintenance.',
      'auto_trans_1359': '1 hour ago',
      'auto_trans_1360': '🕌 Friday Prayer Time Change at Tbilisi Mosque',
      'auto_trans_1361': 'First Friday prayer sermon will start at 1:30 PM instead of 1:00 PM to facilitate students.',
      'auto_trans_1362': '3 hours ago',
      'auto_trans_1363': '⚡ Scheduled Power Cut Next Tuesday',
      'auto_trans_1364': 'Scheduled power cutoff for parts of Didube next Tuesday from 9 AM to 11 AM.',
      'auto_trans_1365': 'Yesterday',
      'auto_trans_1366': 'Now',
      'auto_trans_1367': '💧 Water Cutoff Alert in Saburtalo',
      'auto_trans_1368': 'Attention students in Saburtalo, water will be cut off tomorrow Sunday from 10 AM to 4 PM.',
      'auto_trans_1369': '1 hour ago',
      'auto_trans_1370': '🕌 Friday Prayer at Tbilisi Mosque',
      'auto_trans_1371': 'Friday prayer sermon starts at 1:30 PM to facilitate students.',
      'auto_trans_1372': '3 hours ago',
      'auto_trans_1373': 'Student Service',
      'auto_trans_1374': 'Electrician',
      'auto_trans_1375': 'Maintenance of all electrical faults and connections',
      'auto_trans_1376': 'Plumber',
      'auto_trans_1377': 'Repair of water leaks and plumbing',
      'auto_trans_1378': 'Student Residency Issuance',
      'auto_trans_1379': 'Preparing residency papers for the first time or renewal',
      'auto_trans_1380': 'Legal Address Registration',
      'auto_trans_1381': 'Issuance of certified address document in Georgia',
      'auto_trans_1382': 'University Registration & Transfer',
      'auto_trans_1383': 'Admission procedures and credit transfers',
      'auto_trans_1384': 'Request sent and saved temporarily in the app',
      'auto_trans_1385': 'Now',
      'auto_trans_1386': 'Server connection error',
      'auto_trans_1387': 'Video preview (YouTube/Drive) available on web'
    },
    'ka': {
      'app_title': 'აბშერი (ABSHER)',
      'welcome': 'მოგესალმებით,',
      'home': 'მთავარი',
      'services': 'სერვისები',
      'chat': 'ჩატი',
      'offers': 'შეთავაზებები',
      'profile': 'პროფილი',
      'change_lang': 'ენის შეცვლა (Language)',
      'lang_desc': 'ქართული (Under Dev) / English / العربية',
      'logout': 'ანგარიშიდან გასვლა',
      'guest_logout': 'შესვლის გვერდზე დაბრუნება',
      'guest_mode': 'თქვენ სტუმრის რეჟიმში ხართ!',
      'roommate_match': 'თანაცხოვრების ძიება 🤝',
      'roommate_desc': 'დარეგისტრირდით და ჩვენი გუნდი დაგეხმარებათ ბინის პარტნიორის პოვნაში.',
      'quick_services': 'სტუდენტური სერვისები ⚡',
      'view_all': 'ყველას ნახვა',
      'browse_apts': 'ხელმისაწვდომი სტუდენტური ბინები 🏠',
      'no_commission': 'პირდაპირი სტუდენტური შეთავაზებები 🔥',
      'cash_payment': 'უსაფრთხო ნაღდი ანგარიშსწორება',
      'my_bookings': 'ჩემი ჯავშნები',
      'payment_method': 'გადახდის მეთოდი',
      'contact_support': 'მხარდაჭერასთან დაკავშირება',
      'about_app': 'აბშერის შესახებ',
      'splash_subtitle': 'ABSHER - თქვენი მთავარი სტუდენტური მეგობარი საქართველოში',
      'skip_to_start': 'გამოტოვება და დაწყება >>',
      'login_fail': 'შესვლა ვერ მოხერხდა. გადაამოწმეთ მონაცემები.',
      'login_welcome': 'კეთილი იყოს თქვენი მობრძანება ABSHER-ში',
      'login_subtitle': 'შედით სისტემაში სტუდენტური სერვისების მისაღებად',
      'email_or_phone': 'ელ.ფოსტა ან ტელეფონი',
      'please_enter_email': 'გთხოვთ შეიყვანოთ ელ.ფოსტა ან ტელეფონი',
      'password': 'პაროლი',
      'please_enter_password': 'გთხოვთ შეიყვანოთ პაროლი',
      'contact_support_pw': 'დაუკავშირდით მხარდაჭერას Instagram-ზე @absher_georgia',
      'forgot_pw': 'დაგავიწყდათ პაროლი?',
      'login_btn': 'შესვლა',
      'enter_as_guest': 'სტუმრად შესვლა',
      'no_account_yet': 'ჯერ არ გაქვთ სტუდენტური ანგარიში?',
      'create_new_account': 'ახალი ანგარიშის შექმნა',
      'guest_name': 'სტუმარი',
      'guest_uni': 'საერთო დათვალიერება',
      'other_uni_manual': 'სხვა (ხელით შეყვანა)',
      'register_fail': 'ანგარიშის შექმნა ვერ მოხერხდა. გადაამოწმეთ მონაცემები.',
      'create_account_title': 'ახალი სტუდენტური ანგარიშის შექმნა',
      'create_account_subtitle': 'შემოუერთდით ABSHER-ს და ისარგებლეთ ჩვენი სერვისებით',
      'full_name': 'სრული სახელი',
      'required_field': 'აუცილებელია',
      'email': 'ელ.ფოსტა',
      'invalid_email': 'არასწორი ელ.ფოსტა',
      'phone_example': 'ტელეფონი (მაგ: +995555123456)',
      'georgia_uni': 'უნივერსიტეტი საქართველოში',
      'uni_and_district': 'უნივერსიტეტი და უბანი',
      'please_enter_uni_dist': 'გთხოვთ შეიყვანოთ უნივერსიტეტი და უბანი',
      'pw_min_6': 'მინიმუმ 6 სიმბოლო',
      'create_account_btn': 'ანგარიშის შექმნა ახლა',
      'already_have_account': 'უკვე გაქვთ ანგარიში?',
      'all_flats': 'ყველა ბინა',
      'flat_alone': 'მარტო ცხოვრება',
      'with_roommate': 'თანამცხოვრებთან ერთად',
      'all_districts': 'ყველა უბანი',
      'all': 'ყველა',
      'select_rooms': 'აირჩიეთ ოთახები...',
      'one_room': '1 ოთახი',
      'two_rooms': '2 ოთახი',
      'three_plus_rooms': '3+ ოთახი',
      'filter_flats': 'ფილტრი',
      'rental_type': 'ქირის ტიპი:',
      'district': 'უბანი:',
      'bedrooms': 'საძინებლები:',
      'bathrooms': 'სააბაზანოები:',
      'distance_uni': 'უნივერსიტეტამდე მანძილი:',
      '10_mins': '10 წუთი',
      '20_mins': '20 წუთი',
      '30_mins': '30 წუთი',
      'apply_filter': 'გამოყენება',
      'cancel': 'გაუქმება',
      'select_nearby_unis': '🎓 აირჩიეთ ახლო უნივერსიტეტები',
      'confirm_selection': 'დადასტურება',
      'search_flats': 'ძიება...',
      'no_results': 'შედეგი არ მოიძებნა',
      'details': 'დეტალები',
      'book_now': 'დაჯავშნა',
      'welcome_user': 'მოგესალმებით,',
      'wallet_points': 'საფულე და ქულები',
      'current_points_balance': 'მიმდინარე ქულების ბალანსი',
      'points_usage_desc': 'შეგიძლიათ გამოიყენოთ ქულები სერვისების გადასახდელად',
      'transaction_history': 'ტრანზაქციების ისტორია',
      'no_previous_transactions': 'წინა ტრანზაქციები არ არის',
      'default_student_name': 'პატივცემულო სტუდენტო',
      'default_student_uni': 'საქართველოს უნივერსიტეტი',
      'create_account_now': 'შექმენით სტუდენტური ანგარიში ყველა შეთავაზებით სარგებლობისთვის.',
      'login_or_register': 'შესვლა / რეგისტრაცია',
      'booking_status_subtitle': 'თვალყური ადევნეთ თქვენი ბინის სტატუსს',
      'wallet_subtitle': 'თვალყური ადევნეთ ბალანსს და გადაიხადეთ ქულებით',
      'please_login_wallet': 'გთხოვთ ჯერ გაიაროთ ავტორიზაცია',
      'support_subtitle': 'Instagram @absher_georgia ან ტელეფონით',
      'about_subtitle': 'ვერსია 1.0.0 - ABSHER საქართველოში',
      'clicked_on': 'დააწკაპუნეთ:',
      'available_options': 'ხელმისაწვდომი ვარიანტები',
      'furnished_equipped': 'მოწყობილი და აღჭურვილი ✔️',
      'no_matching_flats': 'ამჟამად შესაბამისი ბინები არ არის.',
      'go_back': 'უკან დაბრუნება',
      'immediate_move_in': 'დაუყოვნებლივ გადასვლა ⚡',
      'click_to_view_images': 'დააწკაპუნეთ სურათების სანახავად და დასაჯავშნად >>',
      'apartment_details': 'ბინის დეტალები',
      'images_count': 'სურათები',
      'apartment_number': 'ბინა #',
      'proximity_label': 'სიახლოვე:',
      'close_to_unis': 'ახლოსაა მთავარ უნივერსიტეტებთან',
      'roommate_reqs_title': 'ქირაობა თანამცხოვრებთან (მოთხოვნები):',
      'roommate_reqs': '👤 თანამცხოვრების მოთხოვნები:',
      'roommate_facilities': '🏠 ხელმისაწვდომი სივრცე და ობიექტები:',
      'features_and_facilities': 'მახასიათებლები და ობიექტები',
      'great_features': 'შესანიშნავი მახასიათებლები',
      'apartment_description': 'ბინის აღწერა',
      'guest_alert_title': 'ყურადღება 🔒',
      'guest_alert_body_booking': 'უკაცრავად, დაჯავშნის მოთხოვნის გასაგზავნად გთხოვთ გაიაროთ ავტორიზაცია.',
      'guest_alert_body_roommate': 'უკაცრავად, თანამცხოვრების მოთხოვნისთვის გთხოვთ გაიაროთ ავტორიზაცია!',
      'choose_housing_method': 'აირჩიეთ საცხოვრებლის მეთოდი',
      'housing_method_desc': 'შეგიძლიათ მარტომ დაჯავშნოთ ბინა ან შეავსოთ თანამცხოვრების ფორმა.',
      'browse_flats': 'ბინების დათვალიერება',
      'browse_flats_desc': 'იხილეთ ხელმისაწვდომი ბინები სურათებით და ფასებით.',
      'all_available_flats': 'ყველა ხელმისაწვდომი ბინა',
      'all_available_flats_desc': 'სტუდენტებისთვის ხელმისაწვდომი ყველა ბინის სია დეტალებითა და ფასებით.',
      'flat_room_choice': 'ოთახის არჩევა ბინაში',
      'flat_room_desc': 'აჩვენეთ ერთი ადამიანისთვის შესაფერისი ბინები და სტუდიები.',
      'flats_for_one': 'ბინები ერთი ადამიანისთვის',
      'flats_for_one_desc': 'მარტოხელა სტუდენტებისთვის განკუთვნილი ბინები და სტუდიები.',
      'roommate_form_title': 'თანამცხოვრების მოთხოვნის ფორმა',
      'roommate_form_desc': 'შეავსეთ თქვენი მონაცემები და ჩვენ დაგიკავშირებთ საუკეთესო თანამცხოვრებს.',
      'full_name_label': 'სრული სახელი',
      'nationality_label': 'ეროვნება',
      'gender_label': 'სქესი',
      'male': 'მამრობითი',
      'female': 'მდედრობითი',
      'males_only': 'მხოლოდ მამრობითი',
      'females_only': 'მხოლოდ მდედრობითი',
      'university_label': 'უნივერსიტეტი',
      'major_label': 'სპეციალობა',
      'major_study_label': 'სწავლის სპეციალობა',
      'whatsapp_number': 'WhatsApp ნომერი',
      'whatsapp_contact_number': 'საკონტაქტო WhatsApp ნომერი',
      'when_move_in': 'როდის გსურთ გადასვლა?',
      'move_in_date_label': 'სასურველი გადასვლის თარიღი',
      'immediate_move': 'დაუყოვნებლივ / რაც შეიძლება მალე',
      'this_month_move': 'ამ თვის განმავლობაში',
      'next_semester_move': 'შემდეგი სემესტრის დასაწყისში',
      'choose_date': 'აირჩიეთ თარიღი',
      'additional_notes': 'დამატებითი შენიშვნები',
      'additional_notes_hint': 'დამატებითი შენიშვნები (მაგ., მოწევა, სიჩუმე და ა.შ.)',
      'send_to_customer_service': 'მომხმარებელთა მომსახურებისთვის გაგზავნა',
      'send_roommate_request': 'მოთხოვნის გაგზავნა მხარდაჭერის ჯგუფისთვის',
      'roommate_match_title': 'სტუდენტური ბინის შერჩევა 🤝',
      'roommate_match_card_title': 'იპოვეთ თავსებადი თანამცხოვრები!',
      'roommate_match_card_desc': 'დაარეგისტრირეთ თქვენი მონაცემები და ბიუჯეტი და ჩვენ დაგიკავშირებთ სტუდენტებს თქვენი უნივერსიტეტიდან.',
      'your_info_and_prefs': 'თქვენი ინფორმაცია და საცხოვრებლის პრეფერენციები',
      'monthly_budget_usd': 'დაახლოებითი ყოველთვიური ბიუჯეტი ერთ ადამიანზე (USD)',
      'housing_type_req': 'სასურველი საცხოვრებლის ტიპი',
      'guest_alert_body_services': 'უკაცრავად, სერვისების მოსათხოვნად გთხოვთ გაიაროთ ავტორიზაცია!',
      'service_form_title': 'სერვისის მოთხოვნის ფორმა',
      'service_form_desc': 'აირჩიეთ სერვისი და შეავსეთ მოთხოვნის დეტალები:',
      'requested_service': 'მოთხოვნილი სერვისი',
      'whatsapp_contact_short': 'საკონტაქტო WhatsApp ნომერი',
      'detailed_address': 'დეტალური მისამართი',
      'best_time_to_execute': 'შესრულების საუკეთესო დრო (კალენდრიდან)',
      'attach_image_optional': 'სურათის დართვა (არასავალდებულო)',
      'image_attached_success': 'სურათი დართულია ✔️',
      'cleaning_details_title': 'მიუთითეთ სახლის ფართობი და სავარაუდო ფასი (3-4 GEL მეტრზე):',
      'number_of_rooms': 'ოთახების რაოდენობა',
      'area_in_meters': 'ფართობი (მეტრი)',
      'estimated_cost': 'სავარაუდო ღირებულება:',
      'currency_gel': 'GEL',
      'notes_details_hint': 'დაწერეთ თქვენი დეტალები და შენიშვნები აქ...',
      'notes_and_details': 'შენიშვნები და შეკვეთის დეტალები',
      'promo_code': 'პრომო კოდი',
      'use_wallet_points': 'გადაიხადეთ საფულის ქულებით',
      'submit_form_confirm': 'ფორმის გაგზავნა და შეკვეთის დადასტურება',
      'all_student_services': 'აბშერის ყველა სტუდენტური სერვისი 🛠️',
      'instant_tag': 'მყისიერი 📝',
      'request_service_button': 'სერვისის მოთხოვნა 🛠️',
      'welcome_chat_msg': 'კეთილი იყოს თქვენი მობრძანება ABSHER-ის პირდაპირ მხარდაჭერაში 🌟! რით შეგვიძლია დაგეხმაროთ დღეს საქართველოში საცხოვრებელთან ან სერვისებთან დაკავშირებით?',
      'rate_customer_service': 'მომხმარებელთა მომსახურების შეფასება',
      'rate_customer_service_desc': 'რამდენად კმაყოფილი ხართ ABSHER-ის ტექნიკური მხარდაჭერის სისწრაფითა და ხარისხით? (მხოლოდ ადმინისტრატორისთვის)',
      'additional_comments_hint': 'დამატებითი შენიშვნები ან კომენტარები...',
      'submit_rating': 'შეფასების გაგზავნა',
      'rating_success_msg': 'თქვენი შეფასება გაიგზავნა ABSHER-ის მენეჯმენტში და წარმატებით შეინახა. გმადლობთ!',
      'attach_link': 'ბმულის დართვა 🔗',
      'enter_or_paste_link': 'შეიყვანეთ ან ჩასვით ნებისმიერი ბმული ჩატში გასაზიარებლად:',
      'url_label': 'ბმული (URL)',
      'send_now': 'გაგზავნა ახლავე',
      'attach_youtube_drive': 'YouTube ან Drive ვიდეოს დართვა 🎥',
      'enter_youtube_drive_link': 'შეიყვანეთ ან ჩასვით ვიდეო ბმული YouTube-დან ან Google Drive-დან:',
      'video_url_label': 'ვიდეოს ბმული (URL)',
      'uploading_file_loading': 'მიმდინარეობს ფაილის ატვირთვა და გაგზავნა... ⏳',
      'file_upload_success': 'ფაილი აიტვირთა და გაიგზავნა წარმატებით! ✅',
      'file_upload_fail': 'უკაცრავად, სერვერზე ფაილის ატვირთვა ვერ მოხერხდა ❌',
      'attach_media_chat': 'ჩატში მედიის დართვა 📎',
      'choose_image_gallery': '📷 სურათის არჩევა გალერეიდან',
      'choose_video_gallery': '🎥 ვიდეოს არჩევა გალერეიდან',
      'manual_link_input': '🔗 ფაილის ბმულის ხელით შეყვანა (გარე საიტი)',
      'preview_video_attachment': '🎥 თანდართული ვიდეოს წინასწარი ნახვა',
      'preview_image_attachment': '📷 თანდართული სურათის წინასწარი ნახვა',
      'video_player_active': 'ვიდეო პლეერი აქტიურია 🎥',
      'absher_support_chat_title': 'ABSHER მენეჯმენტი - მხარდაჭერა და ჩატი',
      'rate_button': 'შეფასება',
      'direct_call_snackbar': 'პირდაპირი სატელეფონო ზარი ან WhatsApp-ით +995555123456',
      'reply_to_message_selected': 'შეტყობინება არჩეულია პასუხის გასაცემად 💬',
      'you': 'თქვენ',
      'tech_support': 'ტექნიკური მხარდაჭერა',
      'click_to_play_video': 'დააწკაპუნეთ ვიდეოს დასაკრავად',
      'reply_to_yourself': 'უპასუხეთ საკუთარ თავს',
      'reply_to_support': 'უპასუხეთ მომხმარებელთა მომსახურებას',
      'attach_image_tooltip': 'სურათის დართვა',
      'attach_video_tooltip': 'ვიდეოს დართვა',
      'attach_link_tooltip': 'ბმულის დართვა',
      'type_message_hint': 'დაწერეთ თქვენი შეტყობინება მენეჯმენტისთვის აქ...',
      'sending_service_request': 'სერვისის მოთხოვნა იგზავნება... ⏳',
      'error_sending_service': 'სერვისის მოთხოვნის გაგზავნის შეცდომა:',
    }
  };

  static String tr(String key) {
    final lang = currentLang.value;
    return _translations[lang]?[key] ?? _translations['ar']?[key] ?? key;
  }
}
