const translations = {
    "ar": {
        "admin_title": "أبشر PRO ADMIN",
        "admin_subtitle": "بوابة التحكم الشاملة في الخدمات والشقق والحسابات",
        "general_stats": "الإحصائيات العامة",
        "customer_service_chat": "شات خدمة العملاء",
        "bookings_requests": "الحجوزات وطلبات السكن",
        "apartments_manage": "إدارة الشقق (مع السعة)",
        "student_services": "الخدمات الطلابية",
        "universities": "الجامعات",
        "districts": "الأحياء السكنية",
        "reviews": "تقييمات وآراء الطلاب",
        "students_accounts": "بيانات وحسابات الطلاب",
        "georgia_news": "أخبار جورجيا 📰",
        "notifications": "التنبيهات والإشعارات 🔔",
        "server_conn": "الاتصال بالخادم:",
        "online_sim": "متصل (المحاكاة نشطة)",
        "add_apartment": "إضافة شقة جديدة",
        "add_service": "إضافة خدمة جديدة",
        "add_university": "إضافة جامعة جديدة",
        "add_district": "إضافة حي جديد",
        "add_student": "إضافة حساب طالب",
        "add_news": "نشر خبر جديد",
        "add_notification": "نشر تنبيه عاجل جديد 🔔",
        "overview_title": "نظرة عامة على نشاط الموقع والتطبيق",
        "overview_subtitle": "ملخص فوري للبيانات المسجلة والحجوزات النشطة",
        "apartments": "الشقق السكنية",
        "available_students": "متاحة للطلاب حالياً",
        "available_services": "الخدمات المتاحة",
        "logistic_services": "خدمة طلابية ولوجستية",
        "students_clients": "الطلاب والعملاء",
        "registered_account": "حساب مسجل بالمنصة",
        "pending_requests": "طلبات قيد المراجعة",
        "needs_followup": "تحتاج لمتابعة الإدارة",
        "quick_add": "⚡ أضف جديداً إلى التطبيق في ثوانٍ!",
        "quick_add_desc": "أي إضافة تقوم بها هنا تنعكس مباشرة في متصفح الموقع وتطبيق الهاتف المحمول فلاتر.",
        "search_apt": "🔍 ابحث برقم الشقة (مثال: 1 أو #1) أو عنوان الشقة...",
        "apt_title": "إدارة الشقق السكنية",
        "apt_desc": "إضافة، تعديل، أو حذف الشقق المعروضة للطلاب في تبليسي",
        "svc_title": "إدارة الخدمات الطلابية",
        "svc_desc": "التحكم في خدمات الصيانة والإقامة والاستقبال",
        "uni_title": "إدارة الجامعات",
        "uni_desc": "إضافة أو حذف الجامعات التي سيتم استخدامها في فلاتر التطبيق",
        "dist_title": "إدارة الأحياء السكنية",
        "dist_desc": "إضافة أو حذف الأحياء السكنية المتاحة في تبليسي والتي سيتم استخدامها في فلتر السكن",
        "chat_title": "شات خدمة العملاء (نظام محادثات فوري)",
        "chat_desc": "المحادثات مرتبة تحت بعضها بشكل عمودي حسب الأحدث وقتاً للرد المباشر والسريع على استفسارات وحجوزات الطلاب",
        "active_chats": "المحادثات النشطة",
        "live": "مباشر",
        "select_chat": "اختر محادثة من القائمة الجانبية (المرتبة حسب الوقت) لعرض استفسارات وحجوزات الطالب والرد عليها فوراً بأسلوب الواتساب.",
        "whatsapp_direct": "وتساب فوري",
        "block": "حظر",
        "reply_to": "↩️ الرد على رسالة:",
        "type_reply": "اكتب رسالتك و ردك على استفسار وحجز الطالب هنا...",
        "upload_image": "تحميل صورة 📷",
        "attach_link": "إرفاق رابط",
        "attach_video": "إرفاق فيديو (تحت التطوير 🚧)",
        "send_reply": "إرسال الرد",
        "req_title": "إدارة الحجوزات وطلبات السكن وتجميع الشباب",
        "req_desc": "متابعة وتحديث حالات طلبات الطلاب الجامعيين مع تفاصيل الحجز الكاملة وإمكانية الرد عبر الواتساب",
        "search_req": "🔍 ابحث برقم الطلب، اسم الطالب، أو رقم الواتساب...",
        "req_num": "# الطلب",
        "student_name": "اسم الطالب",
        "uni_nationality": "الجامعة والجنسية",
        "whatsapp": "الواتساب",
        "svc_details": "نوع الخدمة والتفاصيل",
        "status": "الحالة",
        "actions": "إجراءات",
        "rev_title": "تقييمات وآراء الطلاب في الخدمات والتطبيق",
        "rev_desc": "عرض آراء وانطباعات الطلاب الجامعيين في تبليسي",
        "std_title": "حسابات الطلاب والعملاء",
        "std_desc": "قائمة الحسابات المسجلة في منصة وتطبيق أبشر مع التفاصيل الكاملة",
        "full_name": "الاسم الكامل",
        "email": "البريد الإلكتروني",
        "phone": "رقم الهاتف",
        "registration_date": "تاريخ التسجيل",
        "wallet_points": "نقاط المحفظة",
        "manage_points": "إدارة النقاط",
        "delete": "حذف",
        "news_title": "إدارة أخبار جورجيا",
        "news_desc": "نشر وإدارة الأخبار والمستجدات والمقالات المفيدة للطلاب في جورجيا",
        "attached_image": "الصورة المرفقة",
        "title": "العنوان",
        "content_details": "المحتوى والتفاصيل",
        "publish_date": "تاريخ النشر",
        "notif_title": "إدارة التنبيهات والإشعارات العاجلة",
        "notif_desc": "نشر التنبيهات العاجلة للطلاب (انقطاع مياه/كهرباء، تفاصيل الصلاة والأنشطة). تختفي تلقائياً بعد مرور 48 ساعة.",
        "notif_heading": "عنوان التنبيه",
        "notif_content": "محتوى التنبيه والتفاصيل",
        "notif_status": "حالة التنبيه",
        "manage": "إدارة",
        "cancel": "إلغاء",
        "save_add": "حفظ وإضافة الطالب",
        "execute_op": "تنفيذ العملية وتحديث الرصيد",
        "points_manage_modal": "إدارة نقاط المحفظة للطالب",
        "current_balance": "الرصيد الحالي:",
        "point": "نقطة",
        "op_type": "نوع العملية:",
        "add_points": "إضافة نقاط ➕",
        "withdraw_points": "سحب نقاط ➖",
        "amount_points": "المبلغ / عدد النقاط:",
        "reason_desc": "السبب أو الوصف (يظهر للطالب في الإشعارات):",
        "std_acc_clients": "حسابات الطلاب والعملاء",
        "uni_spec": "الجامعة والتخصص",
        "nationality": "الجنسية",
        "add_new_std_acc": "إضافة حساب طالب جديد",
        "phone_with_code": "رقم الهاتف مع الرمز",
        "ex_ug": "مثال: جامعة جورجيا (UG)",
        "default_pass": "كلمة المرور الافتراضية:",
        "login_pass": "كلمة المرور للدخول",
        "student_name_label": "اسم الطالب",
        "ex_50": "مثال: 50",
        "ex_reward": "مثال: مكافأة تسجيل أو سداد رسوم خدمة...",
        "unspecified": "غير محدد",
        "points_added_notif": "تم إضافة نقاط لمحفظتك 💰",
        "points_deducted_notif": "تم خصم نقاط من محفظتك 📉",
        "points_added_success": "تم إضافة النقاط بنجاح ✅",
        "points_deducted_success": "تم خصم النقاط بنجاح ✅",
        "insufficient_balance": "الرصيد الحالي لا يكفي لعملية الخصم!",
        "delete_confirm_std": "هل أنت متأكد من رغبتك في حذف هذا الحساب؟",
        "acc_deleted_success": "تم حذف الحساب بنجاح 🚫",
        "acc_added_success": "تم إضافة الحساب بنجاح ✅",
        "absher_logo": "أبشر",
        "customer_service_absher": "خدمة العملاء (أبشر)",
        "new_request_badge": "طلب جديد",
        "chat_input_placeholder": "اكتب رسالتك و ردك على استفسار وحجز الطالب هنا...",
        "customer_service_shield": "🛡️ خدمة العملاء (أبشر)",
        "chat_img_att": "📷 صورة مرفقة من خدمة العملاء (أبشر)",
        "status_new_req_yellow": "طلب جديد 🟡",
        "status_new_msg_green": "رسالة جديدة 🟢",
        "status_replied_check": "تم الرد ✔️",
        "status_completed": "مكتمل",
        "status_under_review": "قيد المراجعة",
        "status_in_progress": "جاري التنفيذ",
        "live_status": "Live",
        "general_manager": "المدير العام",
        "server_online": "متصل (المحاكاة نشطة)",
        "chats_subtext": "يتم ترتيب المحادثات عمودياً بأحدث وقت لسرعة الاستجابة لاستفسارات الطلاب وحجوزاتهم",
        "mock_spacious_rooms_0": "غرف واسعة",
        "mock_apartment_for_yourse_1": "شقة بمفردك",
        "mock_delete_2": "حذف",
        "mock_owner_number_copied__3": "تم نسخ رقم المالك بنجاح",
        "mock_ilia_state_4": "إيليا ستيت",
        "mock_delete_apartment_5": "حذف الشقة",
        "mock_district_6": "الحي السكني",
        "mock_room_7": "غرفة",
        "mock_are_you_sure_you_wan_8": "هل أنت متأكد من حظر الطالب",
        "mock_minutes_walk_9": "دقائق مشياً",
        "mock_apartment_number_10": "رقم الشقة",
        "mock_looking_for_a_quiet__11": "أبحث عن شريك هادئ ومحترم لمشاركة شقة",
        "mock_direct_apartment_boo_12": "حجز شقة مباشرة",
        "mock_fully_equipped_with__13": "مجهزة بالكامل بالفرش والأجهزة الكهربائية وتضم",
        "mock_absher_app_is_great_14": "تطبيق أبشر رائع جداً",
        "mock_dollar_15": "دولار",
        "mock_local_image_preview__16": "تم استخدام المعاينة المحلية للصورة",
        "mock_reply_sent_to_studen_17": "تم إرسال ردك إلى الطالب بنجاح وتحديث المحادثة",
        "mock_minutes_18": "دقائق",
        "mock_non_smoker__quiet_st_19": "غير مدخن ، طالب هادئ ومحترم ، يحافظ على النظافة العامة والهدوء",
        "mock_is_it_convenient_for_20": "هل يناسبك معاينته غداً؟",
        "mock_student_added_succes_21": "تم إضافة الطالب بنجاح",
        "mock_tbilisi_medical_univ_22": "جامعة تبليسي الطبية",
        "mock_immediate_23": "فوري",
        "mock_students_24": "طلاب",
        "mock_bag_25": "حقيبة",
        "mock_automated_notificati_26": "وتم إرسال إشعار آلي للطالب في الشات",
        "mock_rent_with_a_roommate_27": "استئجار مع شريك",
        "mock_rooms_28": "غرف",
        "mock_separate_and_comfort_29": "غرف منفصلة ومريحة",
        "mock_mostafa_ali_30": "مصطفى علي",
        "mock_luxury_student_apart_31": "شقة طلابية فاخرة",
        "mock_student_deleted_succ_32": "تم حذف الطالب بنجاح",
        "mock_major_33": "التخصص",
        "mock_new_residential_apar_34": "تمت إضافة شقة سكنية جديدة للإيجار في حي",
        "mock_compressing_and_uplo_35": "جاري ضغط ورفع صورة الخدمة",
        "mock_service_deleted_succ_36": "تم حذف الخدمة بنجاح",
        "mock_failed_to_add_servic_37": "فشل في إضافة الخدمة",
        "mock_replied_38": "تم الرد",
        "mock_includes_customer_re_39": "يتضمن نموذج طلب للعميل",
        "mock_browse_services_sect_40": "تصفح قسم الخدمات للطلب والاستفسار مباشرة",
        "mock_in_progress_41": "جاري التنفيذ",
        "mock_tbilisi_medical_42": "التبليسي الطبية",
        "mock_are_you_sure_you_wan_43": "هل أنت متأكد من رغبتك في حذف هذه الشقة؟",
        "mock_owner_phone_44": "هاتف المالك",
        "mock_that_you_want_to_sen_45": "الذي تريد إرساله للطالب",
        "mock_request_status_updat_46": "تم تحديث حالة الطلب إلى",
        "mock_panoramic_view_47": "إطلالة بنورامية",
        "mock_simulation_active_48": "المحاكاة نشطة",
        "mock_fully_furnished_49": "مفروشة بالكامل",
        "mock_business_administrat_50": "إدارة أعمال",
        "mock_at_price_51": "بسعر",
        "mock_image_upload_failed_52": "فشل رفع الصورة",
        "mock_points_to_your_walle_53": "نقطة إلى محفظتك",
        "mock_new_student_service__54": "تمت إضافة خدمة طلابية جديدة",
        "mock_minute_55": "دقيقة",
        "mock_didube_56": "ديدوبي",
        "mock_please_enter_a_valid_57": "يرجى إدخال مبلغ صحيح أكبر من الصفر",
        "mock_hour_58": "ساعة",
        "mock_upload_failed_59": "فشل الرفع",
        "mock_please_select_a_chat_60": "يرجى تحديد محادثة أولاً",
        "mock_hello__i_would_like__61": "مرحباً، أود حجز الاستوديو المودرن في شارع كوستافا بسعر",
        "mock_move_in_date_62": "موعد الانتقال",
        "mock_date_63": "ميعاد",
        "mock_obtaining_student_re_64": "استخراج إقامة طلابية",
        "mock_chat_now_65": "تحدث الآن",
        "mock_yesterday_66": "أمس",
        "mock_new_message_67": "رسالة جديدة",
        "mock_added_68": "تم إضافة",
        "mock_the_studio_is_curren_69": "الاستوديو متاح حالياً ومفروش بالكامل",
        "mock_airport_reception_an_70": "الاستقبال والنقل من المطار",
        "mock_compressing_and_uplo_71": "جاري ضغط وتحميل الصورة للمستخدم",
        "mock_gldani_72": "جلَداني",
        "mock_completed_73": "مكتمل",
        "mock_month_74": "شهر",
        "mock_university_of_georgi_75": "جامعة جورجيا",
        "mock_now_76": "الآن",
        "mock_shared_apartment_for_77": "شقة مشتركة لـ",
        "mock_alert_deleted_succes_78": "تم حذف التنبيه بنجاح",
        "mock_cash_upon_inspection_79": "نقداً عند معاينة واستلام الشقة",
        "mock_computer_engineering_80": "هندسة حاسبات",
        "mock_near_university_of_g_81": "بالقرب من جامعة جورجيا",
        "mock_sorry__student_balan_82": "عفواً، رصيد الطالب غير كافٍ لهذه العملية",
        "mock_image_attached_by_cu_83": "صورة مرفقة من خدمة العملاء",
        "mock_mtatsminda_84": "متاتسميندا",
        "mock_withdraw_points_85": "سحب نقاط",
        "mock_reply_to_86": "رد على",
        "mock_payment_is_cash_on_d_87": "الدفع يتم نقداً عند الاستلام",
        "mock_no_urgent_alerts_pub_88": "لا يوجد تنبيهات عاجلة منشورة حالياً",
        "mock_room_89": "غرفة",
        "mock_your_reply_was_sent__90": "تم إرسال ردك إلى الطالب وحفظه في السيرفر",
        "mock_female_91": "أنثى",
        "mock_large_hall_for_joint_92": "صالة كبيرة للمذاكرة المشتركة",
        "mock_example_93": "مثال",
        "mock_omar_khaled_94": "عمر خالد",
        "mock_reserved_apartment_95": "الشقة المحجوزة",
        "mock_close_to_supermarket_96": "قريب من السوبرماركت",
        "mock_error_97": "خطأ",
        "mock_male_98": "ذكر",
        "mock_perfect_studio_for_a_99": "ستوديو مثالي للطالب المنفرد الباحث عن الهدوء والتركيز في الدراسة ويحتوي على",
        "mock_room_in_apartment_100": "غرفة في شقة",
        "mock_attached_image_101": "صورة مرفقة",
        "mock_very_large_balcony_102": "بلكونة واسعة جداً",
        "mock_are_you_sure_you_wan_103": "هل أنت متأكد من حذف هذا الحي؟",
        "mock_isani_104": "إساني",
        "mock_image_uploaded_and_s_105": "تم رفع الصورة وإرسالها للطالب بنجاح",
        "mock_apartment_added_and__106": "تمت إضافة الشقة بنجاح ونشرها في التطبيق",
        "mock_please_enter_service_107": "يرجى إدخال اسم الخدمة",
        "mock_image_selected_and_p_108": "تم اختيار الصورة ومُعاينتها بنجاح",
        "mock_attached_video_109": "فيديو مرفق",
        "mock_human_medicine_110": "الطب البشري",
        "mock_egypt_111": "مصر",
        "mock_helped_me_find_accom_112": "ساعدني في العثور على سكن ومطابقة شريك سكن محترم خلال أيام قليلة وبكل سهولة، خدمة ممتازة",
        "mock_number_of_rooms_113": "عدد الغرف",
        "mock_automated_notice_114": "إشعار آلي",
        "mock_recording_voice_note_115": "جاري تسجيل فويس نوت",
        "mock_available_for_partne_116": "المتاح للشريك",
        "mock_customer_service_is__117": "فريق خدمة العملاء سريع جداً في الرد على الشات، والاستقبال من المطار كان في الموعد المحدد بكل احترافية وأمان",
        "mock_clear_118": "مسح",
        "mock_edited_119": "معدلة",
        "mock_since_120": "منذ",
        "mock_we_can_prepare_all_f_121": "يمكننا تجهيز كافة الملفات لك",
        "mock_university_registrat_122": "التسجيل والنقل الجامعي",
        "mock_ago_123": "مضى",
        "mock_excellent_opportunit_124": "فرصة ممتازة لثلاثة أصدقاء طلاب",
        "mock_tbilisi_state_univer_125": "جامعة تبليسي الحكومية",
        "mock_enter_link_126": "أدخل الرابط",
        "mock_hello__i_filled_the__127": "مرحباً، قمت بتعبئة نموذج البحث عن شريك سكن، هل يوجد طالب متوافق معي حالياً؟",
        "mock_points_deducted_succ_128": "تم خصم النقاط بنجاح",
        "mock_completed_129": "مكتمل",
        "mock_human_medicine_130": "الطب البشري",
        "mock_issuing_approved_add_131": "إصدار وثيقة العنوان المعتمدة في جورجيا",
        "mock_dawn__count_132": "فجراً، عدد",
        "mock_jordan_133": "الأردن",
        "mock_new_student_service__134": "خدمة طلابية جديدة متوفرة الآن",
        "mock_legal_address_regist_135": "تسجيل العنوان القانوني",
        "mock_and_close_chat__136": "وإغلاق الشات؟",
        "mock_news_deleted_success_137": "تم حذف الخبر بنجاح",
        "mock_inquiry_regarding_st_138": "استفسار بخصوص أوراق تجديد الإقامة الطلابية المطلوبة هذا العام",
        "mock_chat_139": "شات",
        "mock_youssef_mahmoud_140": "يوسف محمود",
        "mock_saudi_arabia_141": "السعودية",
        "mock_deducted_142": "تم خصم",
        "mock_are_you_sure_you_wan_143": "هل أنت متأكد من رغبتك في مسح هذه الرسالة؟",
        "mock_under_review_144": "قيد المراجعة",
        "mock_are_you_sure_you_wan_145": "هل أنت متأكد من رغبتك في حذف هذه الخدمة؟",
        "mock_sara_mohamed_146": "سارة محمد",
        "mock_news_image_uploaded__147": "تم رفع صورة الخبر بنجاح",
        "mock_egypt_148": "مصر",
        "mock_ilia_state_universit_149": "جامعة إيليا الحكومية",
        "mock_service_request_150": "طلب خدمة",
        "mock_manage_151": "إدارة",
        "mock_image_successfully_152": "صورة بنجاح",
        "mock_warm_central_heating_153": "تدفئة مركزية دافئة",
        "mock_pekini_street_154": "شارع بيكيني",
        "mock_delete_service_155": "حذف الخدمة",
        "mock_business_administrat_156": "إدارة أعمال",
        "mock_reply_157": "الرد",
        "mock_kostava_street_158": "شارع كوستافا",
        "mock_apartment_image_159": "صورة شقة",
        "mock_online_160": "متصل",
        "mock_uploaded_161": "تم رفع",
        "mock_bathroom_162": "حمام",
        "mock_compressing_and_uplo_163": "جاري ضغط ورفع",
        "mock_airport_reception_an_164": "الاستقبال والنقل من المطار",
        "mock_thank_you__studio_vi_165": "شكراً لكم، تم تأكيد موعد معاينة الاستوديو غداً صباحاً",
        "mock_maintenance_of_all_e_166": "صيانة كافة الأعطال والتوصيلات الكهربائية",
        "mock_admission_procedures_167": "إجراءات القبول وتحويل الساعات بين الجامعات",
        "mock_this_message_was_del_168": "تم حذف هذه الرسالة من قبل خدمة العملاء",
        "mock_minute_169": "دقيقة",
        "mock_district_added_succe_170": "تمت إضافة الحي بنجاح",
        "mock_human_medicine_171": "الطب البشري",
        "mock_attach_image_172": "إرفاق صورة",
        "mock_active_in_app_173": "نشطة في التطبيق",
        "mock_playing_voice_record_174": "جاري تشغيل التسجيل الصوتي",
        "mock_independent_bathroom_175": "حمام مستقل",
        "mock_no_news_or_alerts_pu_176": "لا يوجد أخبار أو تنبيهات منشورة حالياً",
        "mock_customer_service_177": "خدمة العملاء",
        "mock_immediate_178": "فوري",
        "mock_welcome_sara_to_absh_179": "أهلاً بك سارة في أبشر",
        "mock_payment_method_180": "طريقة الدفع",
        "mock_absher_181": "أبشر",
        "mock_quiet_single_studio_182": "ستوديو منفرد هادئ",
        "mock_business_administrat_183": "إدارة أعمال",
        "mock_hello_khaled__requir_184": "مرحباً خالد، المطلوب شهادة طالب حديثة وكشف حساب بنكي وعقد السكن القانوني",
        "mock_ahmed_gamal_185": "أحمد جمال",
        "mock_points_added_success_186": "تم إضافة النقاط بنجاح",
        "mock_customer_service_187": "خدمة العملاء",
        "mock_partner_conditions_188": "شروط الشريك",
        "mock_balcony_with_open_vi_189": "بلكونة بإطلالة مفتوحة",
        "mock_plumber_190": "فني سباكة",
        "mock_minutes_walk_from_un_191": "دقائق مشياً عن حرم جامعة جورجيا",
        "mock_new_192": "جديدة",
        "mock_click_to_open_image__193": "اضغط لفتح الصورة بحجم كامل",
        "mock_delete_194": "حذف",
        "mock_expired_195": "منتهي الصلاحية",
        "mock_room_near_the_medica_196": "غرفة قريبة من الجامعة الميديكال",
        "mock_computer_engineering_197": "هندسة حاسبات",
        "mock_university_added_suc_198": "تم إضافة الجامعة بنجاح",
        "mock_arrival_time_199": "موعد الوصول",
        "mock_attached_link_200": "رابط مرفق",
        "mock_reason_201": "السبب",
        "mock_apartment_deleted_su_202": "تم حذف الشقة بنجاح",
        "mock_gender_203": "النوع",
        "mock_spacious_balcony_204": "بلكونة واسعة",
        "mock_new_residential_apar_205": "شقة سكنية جديدة معروضة للإيجار",
        "mock_electrician_206": "فني كهربائي",
        "mock_attachment_207": "مرفق",
        "mock_reply_to_this_messag_208": "الرد على هذه الرسالة",
        "mock_student_blocked_209": "تم حظر الطالب",
        "mock_blocked_210": "محظور",
        "mock_your_request_status__211": "تم تحديث حالة طلبك",
        "mock_apartment_212": "شقة",
        "mock_in_progress_213": "جاري التنفيذ",
        "mock_video_attach_feature_214": "ميزة إرفاق الفيديو تحت التطوير حالياً، يمكنك إرفاق رابط صورة أو تحميل صورة مباشرة",
        "mock_am_215": "صباحاً",
        "mock_vake_216": "فاكي",
        "mock_chat_archived_succes_217": "تمت أرشفة المحادثة بنجاح",
        "mock_active_and_effective_218": "نشط وفعال للطالب",
        "mock_district_deleted_suc_219": "تم حذف الحي بنجاح",
        "mock_are_you_sure_you_wan_220": "هل أنت متأكد من رغبتك في حذف هذا الخبر نهائياً؟",
        "mock_status_221": "وضع",
        "mock_hello_customer_servi_222": "مرحباً خدمة العملاء، قمت بتعبئة نموذج البحث عن شريك سكن لشقة في شارع بيكيني",
        "mock_ilia_state_universit_223": "جامعة إيليا الحكومية",
        "mock_university_deleted_s_224": "تم حذف الجامعة بنجاح",
        "mock_away_225": "يبعد",
        "mock_message_deleted_succ_226": "تم حذف الرسالة بنجاح",
        "mock_saburtalo_227": "سابورتالو",
        "mock_roommate_228": "شريك سكن",
        "mock_private_furnished_be_229": "غرفة نوم خاصة ومفروشة ، حمام ومطبخ مشترك ، شرفة",
        "mock_service_image_upload_230": "تم رفع صورة الخدمة بنجاح",
        "mock_message_edited_succe_231": "تم تعديل الرسالة بنجاح",
        "mock_recorded_voice_note_232": "فويس نوت صوتي مسجل",
        "mock_voice_recording_sent_233": "تم إرسال التسجيل الصوتي بنجاح",
        "mock_are_you_sure_you_wan_234": "هل أنت متأكد من حذف هذا الطالب نهائياً؟",
        "mock_uploading_news_image_235": "جاري رفع صورة الخبر",
        "mock_ac_and_heating_236": "تكييف وتدفئة",
        "mock_number_237": "رقم",
        "mock_preparing_residency__238": "تجهيز أوراق الإقامة لأول مرة أو التجديد",
        "mock_unknown_error_239": "خطأ غير معروف",
        "mock_error_connecting_to__240": "حدث خطأ أثناء الاتصال بالخادم",
        "mock_bathroom_and_excelle_241": "حمام وتوزيع ممتاز للغرف يضمن الخصوصية لكل طالب",
        "mock_unspecified_242": "غير محدد",
        "mock_excellent_student_ap_243": "شقة ممتازة للطلاب في قلب تبليسي بالقرب من محطة مترو التكنيكال",
        "mock_thursday_at_244": "يوم الخميس الساعة",
        "mock___with_you_is_absher_245": "، معك خدمة عملاء تطبيق أبشر",
        "mock_modern_studio_246": "ستوديو مودرن",
        "mock_spacious_area_includ_247": "مساحة واسعة وتضم",
        "mock_student_service_requ_248": "طلب خدمة طلابية",
        "mock_points_from_your_wal_249": "نقطة من محفظتك",
        "mock_hello_250": "مرحباً",
        "mock_edit_message_text_251": "تعديل نص الرسالة",
        "mock_ilia_university_252": "جامعة إيليا",
        "mock_tbilisi_state_univer_253": "جامعة تبليسي الحكومية",
        "mock_apartment_options_ar_254": "خيارات الشقق ممتازة ومفروشة بالكامل والأسعار مناسبة جداً لميزانية الطلاب في تبليسي",
        "mock_error_connecting_to__255": "حدث خطأ أثناء الاتصال بالخادم عند إضافة الخدمة",
        "mock_saudi_arabia_256": "السعودية",
        "mock_alert_published_succ_257": "تم نشر التنبيه بنجاح",
        "mock_nationality_258": "الجنسية",
        "mock_jordan_259": "الأردن",
        "mock_bathroom_with_wonder_260": "حمام مع إطلالة رائعة من البلكونة",
        "mock_news_published_succe_261": "تم نشر الخبر بنجاح",
        "mock_add_points_262": "إضافة نقاط",
        "mock_thank_you_very_much__263": "شكراً جزيلاً على سرعة الرد والمساعدة في الإقامة",
        "mock_ilia_state_264": "إيليا ستيت",
        "mock_replied_265": "تم الرد",
        "mock_security_around_266": "أمن على مدار",
        "mock_notes_267": "الملاحظات",
        "mock_service_added_succes_268": "تمت إضافة الخدمة بنجاح إلى قائمة الخدمات",
        "mock_immediate_move_in_269": "انتقال فوري",
        "mock_under_review_270": "قيد المراجعة",
        "mock_available_for_reques_271": "متاحة للطلب",
        "mock_student_blocked_and__272": "تم حظر الطالب وإغلاق المحادثة بنجاح",
        "mock_explain_housing_and__273": "شرح تفاصيل السكن والحجز",
        "mock_group_of_youth_274": "تجميع شباب",
        "mock_hello_customer_servi_275": "مرحباً خدمة العملاء",
        "mock_browse_housing_scree_276": "تصفح شاشات السكن للاطلاع على الصور والتفاصيل كاملة",
        "mock_provide_comfortable__277": "توفير سيارات مريحة لاستقبالك فور وصولك تبليسي",
        "mock_university_of_georgi_278": "جامعة جورجيا",
        "mock_edit_message_279": "تعديل الرسالة",
        "mock_this_account_has_bee_280": "تم حظر هذا الحساب من قبل إدارة خدمة العملاء ولن يتم استقبال رسائل جديدة",
        "mock_to_281": "إلى",
        "mock_hello_282": "مرحباً",
        "mock_open_chat_with_stude_283": "فتح المحادثة مع الطالب",
        "mock_archived_284": "مؤرشفة",
        "mock_university_285": "الجامعة",
        "mock_delete_286": "حذف",
        "mock_requested_service_287": "الخدمة المطلوبة",
        "mock_is_there_a_matching__288": "هل يوجد طالب متوافق معي حالياً جاهز للانتقال الفوري؟",
        "mock_reem_ahmed_289": "ريم أحمد",
        "mock_modern_studio_290": "ستوديو مودرن",
        "mock_attached_link_291": "رابط مرفق",
        "mock_repairing_water_leak_292": "إصلاح تسريبات المياه والصيانة الصحية",
        "mock_website_link_or_onli_293": "رابط موقع أو ملف أونلاين",
        "mock_dollars_per_person_294": "دولار للشخص",
        "mock_delete_message_295": "حذف الرسالة",
        "mock_are_you_sure_you_wan_296": "هل أنت متأكد من رغبتك في حذف هذا التنبيه نهائياً؟",
        "mock_khaled_abdullah_297": "خالد عبد الله",
        "mock_nationality_298": "الجنسية",
        "mock_working_elevator_299": "مصعد يعمل",
        "mock_are_you_sure_you_wan_300": "هل أنت متأكد من حذف هذه الجامعة؟",
        "mock_two_hours_ago_301": "منذ ساعتين",
        "mock_yes_302": "نعم",
        "mock_fast_fiber_optic_int_303": "إنترنت ألياف ضوئية سريع",
        "mock_interactive_local_st_304": "وضع التخزين المحلي التفاعلي"
    },
    "en": {
        "admin_title": "Absher PRO ADMIN",
        "admin_subtitle": "Comprehensive control portal for services, apartments, and accounts",
        "general_stats": "General Statistics",
        "customer_service_chat": "Customer Service Chat",
        "bookings_requests": "Bookings & Requests",
        "apartments_manage": "Manage Apartments (w/ Capacity)",
        "student_services": "Student Services",
        "universities": "Universities",
        "districts": "Districts",
        "reviews": "Student Reviews",
        "students_accounts": "Student Accounts",
        "georgia_news": "Georgia News 📰",
        "notifications": "Alerts & Notifications 🔔",
        "server_conn": "Server Connection:",
        "online_sim": "Online (Simulation Active)",
        "add_apartment": "Add New Apartment",
        "add_service": "Add New Service",
        "add_university": "Add New University",
        "add_district": "Add New District",
        "add_student": "Add Student Account",
        "add_news": "Publish New News",
        "add_notification": "Publish Urgent Alert 🔔",
        "overview_title": "Site & App Activity Overview",
        "overview_subtitle": "Instant summary of registered data and active bookings",
        "apartments": "Apartments",
        "available_students": "Currently available for students",
        "available_services": "Available Services",
        "logistic_services": "Student and logistics service",
        "students_clients": "Students & Clients",
        "registered_account": "Account registered on platform",
        "pending_requests": "Pending Requests",
        "needs_followup": "Needs management follow-up",
        "quick_add": "⚡ Add new to app in seconds!",
        "quick_add_desc": "Any addition you make here reflects directly in the website browser and Flutter mobile app.",
        "search_apt": "🔍 Search by apartment number (e.g. 1 or #1) or address...",
        "apt_title": "Manage Apartments",
        "apt_desc": "Add, edit, or delete apartments shown to students in Tbilisi",
        "svc_title": "Manage Student Services",
        "svc_desc": "Control maintenance, accommodation, and reception services",
        "uni_title": "Manage Universities",
        "uni_desc": "Add or delete universities used in app filters",
        "dist_title": "Manage Districts",
        "dist_desc": "Add or delete districts available in Tbilisi used in housing filters",
        "chat_title": "Customer Service Chat (Instant Messaging)",
        "chat_desc": "Chats are arranged vertically by latest time for direct and quick response to student inquiries and bookings",
        "active_chats": "Active Chats",
        "live": "Live",
        "select_chat": "Select a chat from the sidebar (sorted by time) to view student inquiries and reply instantly like WhatsApp.",
        "whatsapp_direct": "Direct WhatsApp",
        "block": "Block",
        "reply_to": "↩️ Reply to:",
        "type_reply": "Type your message and reply to student here...",
        "upload_image": "Upload Image 📷",
        "attach_link": "Attach Link",
        "attach_video": "Attach Video (WIP 🚧)",
        "send_reply": "Send Reply",
        "req_title": "Manage Bookings, Housing & Roommates",
        "req_desc": "Track and update university student request statuses with full booking details and WhatsApp reply option",
        "search_req": "🔍 Search by request #, student name, or WhatsApp...",
        "req_num": "Request #",
        "student_name": "Student Name",
        "uni_nationality": "University & Nationality",
        "whatsapp": "WhatsApp",
        "svc_details": "Service Type & Details",
        "status": "Status",
        "actions": "Actions",
        "rev_title": "Student Reviews & Opinions",
        "rev_desc": "View opinions and impressions of university students in Tbilisi",
        "std_title": "Student & Client Accounts",
        "std_desc": "List of accounts registered in Absher platform with full details",
        "full_name": "Full Name",
        "email": "Email Address",
        "phone": "Phone Number",
        "registration_date": "Registration Date",
        "wallet_points": "Wallet Points",
        "manage_points": "Manage Points",
        "delete": "Delete",
        "news_title": "Manage Georgia News",
        "news_desc": "Publish and manage news, updates, and useful articles for students in Georgia",
        "attached_image": "Attached Image",
        "title": "Title",
        "content_details": "Content & Details",
        "publish_date": "Publish Date",
        "notif_title": "Manage Urgent Alerts & Notifications",
        "notif_desc": "Publish urgent alerts to students (water/electricity cuts, prayer details). Disappears automatically after 48 hours.",
        "notif_heading": "Alert Title",
        "notif_content": "Alert Content & Details",
        "notif_status": "Alert Status",
        "manage": "Manage",
        "cancel": "Cancel",
        "save_add": "Save & Add Student",
        "execute_op": "Execute Operation & Update Balance",
        "points_manage_modal": "Manage Student Wallet Points",
        "current_balance": "Current Balance:",
        "point": "Point",
        "op_type": "Operation Type:",
        "add_points": "Add Points ➕",
        "withdraw_points": "Withdraw Points ➖",
        "amount_points": "Amount / Number of Points:",
        "reason_desc": "Reason or Description (shows to student):",
        "std_acc_clients": "Student & Client Accounts",
        "uni_spec": "University & Specialization",
        "nationality": "Nationality",
        "add_new_std_acc": "Add New Student Account",
        "phone_with_code": "Phone number with code",
        "ex_ug": "e.g. University of Georgia (UG)",
        "default_pass": "Default Password:",
        "login_pass": "Login Password",
        "student_name_label": "Student Name",
        "ex_50": "e.g. 50",
        "ex_reward": "e.g. Signup bonus or service fee payment...",
        "unspecified": "Unspecified",
        "points_added_notif": "Points added to your wallet 💰",
        "points_deducted_notif": "Points deducted from your wallet 📉",
        "points_added_success": "Points added successfully ✅",
        "points_deducted_success": "Points deducted successfully ✅",
        "insufficient_balance": "Current balance is insufficient for deduction!",
        "delete_confirm_std": "Are you sure you want to delete this account?",
        "acc_deleted_success": "Account deleted successfully 🚫",
        "acc_added_success": "Account added successfully ✅",
        "absher_logo": "Absher",
        "customer_service_absher": "Customer Service (Absher)",
        "new_request_badge": "New Request",
        "chat_input_placeholder": "Type your message and reply to student inquiry here...",
        "customer_service_shield": "🛡️ Customer Service (Absher)",
        "chat_img_att": "📷 Attached image from Customer Service (Absher)",
        "status_new_req_yellow": "New Request 🟡",
        "status_new_msg_green": "New Message 🟢",
        "status_replied_check": "Replied ✔️",
        "status_completed": "Completed",
        "status_under_review": "Under Review",
        "status_in_progress": "In Progress",
        "live_status": "Live",
        "general_manager": "General Manager",
        "server_online": "Online (Simulation Active)",
        "chats_subtext": "Chats are arranged vertically by latest time for direct and quick response to student inquiries and bookings",
        "mock_spacious_rooms_0": "Spacious Rooms",
        "mock_apartment_for_yourse_1": "Apartment for yourself",
        "mock_delete_2": "Delete",
        "mock_owner_number_copied__3": "Owner number copied successfully",
        "mock_ilia_state_4": "Ilia State",
        "mock_delete_apartment_5": "Delete Apartment",
        "mock_district_6": "District",
        "mock_room_7": "Room",
        "mock_are_you_sure_you_wan_8": "Are you sure you want to block this student",
        "mock_minutes_walk_9": "Minutes walk",
        "mock_apartment_number_10": "Apartment Number",
        "mock_looking_for_a_quiet__11": "Looking for a quiet and respectful roommate to share an apartment",
        "mock_direct_apartment_boo_12": "Direct Apartment Booking",
        "mock_fully_equipped_with__13": "Fully equipped with furniture and appliances, includes",
        "mock_absher_app_is_great_14": "Absher app is great",
        "mock_dollar_15": "Dollar",
        "mock_local_image_preview__16": "Local image preview used",
        "mock_reply_sent_to_studen_17": "Reply sent to student and chat updated",
        "mock_minutes_18": "Minutes",
        "mock_non_smoker__quiet_st_19": "Non-smoker, quiet student, maintains cleanliness and calm",
        "mock_is_it_convenient_for_20": "Is it convenient for you to view it tomorrow?",
        "mock_student_added_succes_21": "Student added successfully",
        "mock_tbilisi_medical_univ_22": "Tbilisi Medical University",
        "mock_immediate_23": "Immediate",
        "mock_students_24": "Students",
        "mock_bag_25": "Bag",
        "mock_automated_notificati_26": "Automated notification sent to student in chat",
        "mock_rent_with_a_roommate_27": "Rent with a roommate",
        "mock_rooms_28": "Rooms",
        "mock_separate_and_comfort_29": "Separate and comfortable rooms",
        "mock_mostafa_ali_30": "Mostafa Ali",
        "mock_luxury_student_apart_31": "Luxury Student Apartment",
        "mock_student_deleted_succ_32": "Student deleted successfully",
        "mock_major_33": "Major",
        "mock_new_residential_apar_34": "New residential apartment added for rent in district",
        "mock_compressing_and_uplo_35": "Compressing and uploading service image",
        "mock_service_deleted_succ_36": "Service deleted successfully",
        "mock_failed_to_add_servic_37": "Failed to add service",
        "mock_replied_38": "Replied",
        "mock_includes_customer_re_39": "Includes customer request form",
        "mock_browse_services_sect_40": "Browse services section to request and inquire directly",
        "mock_in_progress_41": "In Progress",
        "mock_tbilisi_medical_42": "Tbilisi Medical",
        "mock_are_you_sure_you_wan_43": "Are you sure you want to delete this apartment?",
        "mock_owner_phone_44": "Owner Phone",
        "mock_that_you_want_to_sen_45": "that you want to send to the student",
        "mock_request_status_updat_46": "Request status updated to",
        "mock_panoramic_view_47": "Panoramic view",
        "mock_simulation_active_48": "Simulation Active",
        "mock_fully_furnished_49": "Fully Furnished",
        "mock_business_administrat_50": "Business Administration",
        "mock_at_price_51": "at price",
        "mock_image_upload_failed_52": "Image upload failed",
        "mock_points_to_your_walle_53": "points to your wallet",
        "mock_new_student_service__54": "New student service added",
        "mock_minute_55": "minute",
        "mock_didube_56": "Didube",
        "mock_please_enter_a_valid_57": "Please enter a valid amount greater than zero",
        "mock_hour_58": "hour",
        "mock_upload_failed_59": "Upload failed",
        "mock_please_select_a_chat_60": "Please select a chat first",
        "mock_hello__i_would_like__61": "Hello, I would like to book the modern studio on Kostava Street for",
        "mock_move_in_date_62": "Move-in date",
        "mock_date_63": "Date",
        "mock_obtaining_student_re_64": "Obtaining student residency",
        "mock_chat_now_65": "Chat Now",
        "mock_yesterday_66": "Yesterday",
        "mock_new_message_67": "New Message",
        "mock_added_68": "Added",
        "mock_the_studio_is_curren_69": "The studio is currently available and fully furnished",
        "mock_airport_reception_an_70": "Airport reception and transfer",
        "mock_compressing_and_uplo_71": "Compressing and uploading image for user",
        "mock_gldani_72": "Gldani",
        "mock_completed_73": "Completed",
        "mock_month_74": "Month",
        "mock_university_of_georgi_75": "University of Georgia",
        "mock_now_76": "Now",
        "mock_shared_apartment_for_77": "Shared apartment for",
        "mock_alert_deleted_succes_78": "Alert deleted successfully",
        "mock_cash_upon_inspection_79": "Cash upon inspection and receiving the apartment",
        "mock_computer_engineering_80": "Computer Engineering",
        "mock_near_university_of_g_81": "Near University of Georgia",
        "mock_sorry__student_balan_82": "Sorry, student balance is insufficient for this operation",
        "mock_image_attached_by_cu_83": "Image attached by Customer Service",
        "mock_mtatsminda_84": "Mtatsminda",
        "mock_withdraw_points_85": "Withdraw points",
        "mock_reply_to_86": "Reply to",
        "mock_payment_is_cash_on_d_87": "Payment is cash on delivery",
        "mock_no_urgent_alerts_pub_88": "No urgent alerts published currently",
        "mock_room_89": "Room",
        "mock_your_reply_was_sent__90": "Your reply was sent to the student and saved to server",
        "mock_female_91": "Female",
        "mock_large_hall_for_joint_92": "Large hall for joint study",
        "mock_example_93": "Example",
        "mock_omar_khaled_94": "Omar Khaled",
        "mock_reserved_apartment_95": "Reserved apartment",
        "mock_close_to_supermarket_96": "Close to supermarket",
        "mock_error_97": "Error",
        "mock_male_98": "Male",
        "mock_perfect_studio_for_a_99": "Perfect studio for a single student looking for quiet study, includes",
        "mock_room_in_apartment_100": "Room in apartment",
        "mock_attached_image_101": "Attached Image",
        "mock_very_large_balcony_102": "Very large balcony",
        "mock_are_you_sure_you_wan_103": "Are you sure you want to delete this district?",
        "mock_isani_104": "Isani",
        "mock_image_uploaded_and_s_105": "Image uploaded and sent to student successfully",
        "mock_apartment_added_and__106": "Apartment added and published in app successfully",
        "mock_please_enter_service_107": "Please enter service name",
        "mock_image_selected_and_p_108": "Image selected and previewed successfully",
        "mock_attached_video_109": "Attached Video",
        "mock_human_medicine_110": "Human Medicine",
        "mock_egypt_111": "Egypt",
        "mock_helped_me_find_accom_112": "Helped me find accommodation and match a respectful roommate easily within days, excellent service",
        "mock_number_of_rooms_113": "Number of Rooms",
        "mock_automated_notice_114": "Automated Notice",
        "mock_recording_voice_note_115": "Recording voice note",
        "mock_available_for_partne_116": "Available for partner",
        "mock_customer_service_is__117": "Customer service is fast to respond, and airport pickup was on time and professional",
        "mock_clear_118": "Clear",
        "mock_edited_119": "Edited",
        "mock_since_120": "Since",
        "mock_we_can_prepare_all_f_121": "We can prepare all files for you",
        "mock_university_registrat_122": "University registration and transfer",
        "mock_ago_123": "Ago",
        "mock_excellent_opportunit_124": "Excellent opportunity for three student friends",
        "mock_tbilisi_state_univer_125": "Tbilisi State University",
        "mock_enter_link_126": "Enter link",
        "mock_hello__i_filled_the__127": "Hello, I filled the roommate search form, is there any matching student currently?",
        "mock_points_deducted_succ_128": "Points deducted successfully",
        "mock_completed_129": "Completed",
        "mock_human_medicine_130": "Human Medicine",
        "mock_issuing_approved_add_131": "Issuing approved address document in Georgia",
        "mock_dawn__count_132": "Dawn, count",
        "mock_jordan_133": "Jordan",
        "mock_new_student_service__134": "New student service available now",
        "mock_legal_address_regist_135": "Legal address registration",
        "mock_and_close_chat__136": "and close chat?",
        "mock_news_deleted_success_137": "News deleted successfully",
        "mock_inquiry_regarding_st_138": "Inquiry regarding student residency renewal documents required this year",
        "mock_chat_139": "Chat",
        "mock_youssef_mahmoud_140": "Youssef Mahmoud",
        "mock_saudi_arabia_141": "Saudi Arabia",
        "mock_deducted_142": "Deducted",
        "mock_are_you_sure_you_wan_143": "Are you sure you want to delete this message?",
        "mock_under_review_144": "Under Review",
        "mock_are_you_sure_you_wan_145": "Are you sure you want to delete this service?",
        "mock_sara_mohamed_146": "Sara Mohamed",
        "mock_news_image_uploaded__147": "News image uploaded successfully",
        "mock_egypt_148": "Egypt",
        "mock_ilia_state_universit_149": "Ilia State University",
        "mock_service_request_150": "Service Request",
        "mock_manage_151": "Manage",
        "mock_image_successfully_152": "Image successfully",
        "mock_warm_central_heating_153": "Warm central heating",
        "mock_pekini_street_154": "Pekini Street",
        "mock_delete_service_155": "Delete Service",
        "mock_business_administrat_156": "Business Administration",
        "mock_reply_157": "Reply",
        "mock_kostava_street_158": "Kostava Street",
        "mock_apartment_image_159": "Apartment Image",
        "mock_online_160": "Online",
        "mock_uploaded_161": "Uploaded",
        "mock_bathroom_162": "Bathroom",
        "mock_compressing_and_uplo_163": "Compressing and uploading",
        "mock_airport_reception_an_164": "Airport reception and transfer",
        "mock_thank_you__studio_vi_165": "Thank you, studio viewing confirmed for tomorrow morning",
        "mock_maintenance_of_all_e_166": "Maintenance of all electrical faults and connections",
        "mock_admission_procedures_167": "Admission procedures and credit transfer between universities",
        "mock_this_message_was_del_168": "This message was deleted by customer service",
        "mock_minute_169": "minute",
        "mock_district_added_succe_170": "District added successfully",
        "mock_human_medicine_171": "Human Medicine",
        "mock_attach_image_172": "Attach Image",
        "mock_active_in_app_173": "Active in App",
        "mock_playing_voice_record_174": "Playing voice recording",
        "mock_independent_bathroom_175": "Independent bathroom",
        "mock_no_news_or_alerts_pu_176": "No news or alerts published currently",
        "mock_customer_service_177": "Customer Service",
        "mock_immediate_178": "Immediate",
        "mock_welcome_sara_to_absh_179": "Welcome Sara to Absher",
        "mock_payment_method_180": "Payment Method",
        "mock_absher_181": "Absher",
        "mock_quiet_single_studio_182": "Quiet single studio",
        "mock_business_administrat_183": "Business Administration",
        "mock_hello_khaled__requir_184": "Hello Khaled, required is a recent student certificate, bank statement, and legal housing contract",
        "mock_ahmed_gamal_185": "Ahmed Gamal",
        "mock_points_added_success_186": "Points added successfully",
        "mock_customer_service_187": "Customer Service",
        "mock_partner_conditions_188": "Partner Conditions",
        "mock_balcony_with_open_vi_189": "Balcony with open view",
        "mock_plumber_190": "Plumber",
        "mock_minutes_walk_from_un_191": "Minutes walk from University of Georgia campus",
        "mock_new_192": "New",
        "mock_click_to_open_image__193": "Click to open image full size",
        "mock_delete_194": "Delete",
        "mock_expired_195": "Expired",
        "mock_room_near_the_medica_196": "Room near the Medical University",
        "mock_computer_engineering_197": "Computer Engineering",
        "mock_university_added_suc_198": "University added successfully",
        "mock_arrival_time_199": "Arrival Time",
        "mock_attached_link_200": "Attached Link",
        "mock_reason_201": "Reason",
        "mock_apartment_deleted_su_202": "Apartment deleted successfully",
        "mock_gender_203": "Gender",
        "mock_spacious_balcony_204": "Spacious balcony",
        "mock_new_residential_apar_205": "New residential apartment for rent",
        "mock_electrician_206": "Electrician",
        "mock_attachment_207": "Attachment",
        "mock_reply_to_this_messag_208": "Reply to this message",
        "mock_student_blocked_209": "Student blocked",
        "mock_blocked_210": "Blocked",
        "mock_your_request_status__211": "Your request status updated",
        "mock_apartment_212": "Apartment",
        "mock_in_progress_213": "In Progress",
        "mock_video_attach_feature_214": "Video attach feature is under development, you can attach a link or upload an image directly",
        "mock_am_215": "AM",
        "mock_vake_216": "Vake",
        "mock_chat_archived_succes_217": "Chat archived successfully",
        "mock_active_and_effective_218": "Active and effective for student",
        "mock_district_deleted_suc_219": "District deleted successfully",
        "mock_are_you_sure_you_wan_220": "Are you sure you want to permanently delete this news?",
        "mock_status_221": "Status",
        "mock_hello_customer_servi_222": "Hello customer service, I filled out the roommate search form for an apartment in Pekini Street",
        "mock_ilia_state_universit_223": "Ilia State University",
        "mock_university_deleted_s_224": "University deleted successfully",
        "mock_away_225": "Away",
        "mock_message_deleted_succ_226": "Message deleted successfully",
        "mock_saburtalo_227": "Saburtalo",
        "mock_roommate_228": "Roommate",
        "mock_private_furnished_be_229": "Private furnished bedroom, shared bathroom and kitchen, balcony",
        "mock_service_image_upload_230": "Service image uploaded successfully",
        "mock_message_edited_succe_231": "Message edited successfully",
        "mock_recorded_voice_note_232": "Recorded voice note",
        "mock_voice_recording_sent_233": "Voice recording sent successfully",
        "mock_are_you_sure_you_wan_234": "Are you sure you want to delete this student permanently?",
        "mock_uploading_news_image_235": "Uploading news image",
        "mock_ac_and_heating_236": "AC and Heating",
        "mock_number_237": "Number",
        "mock_preparing_residency__238": "Preparing residency papers for the first time or renewal",
        "mock_unknown_error_239": "Unknown Error",
        "mock_error_connecting_to__240": "Error connecting to server",
        "mock_bathroom_and_excelle_241": "Bathroom and excellent room distribution ensures privacy for each student",
        "mock_unspecified_242": "Unspecified",
        "mock_excellent_student_ap_243": "Excellent student apartment in the heart of Tbilisi near Technical Metro Station",
        "mock_thursday_at_244": "Thursday at",
        "mock___with_you_is_absher_245": ", with you is Absher app customer service",
        "mock_modern_studio_246": "Modern Studio",
        "mock_spacious_area_includ_247": "Spacious area includes",
        "mock_student_service_requ_248": "Student Service Request",
        "mock_points_from_your_wal_249": "points from your wallet",
        "mock_hello_250": "Hello",
        "mock_edit_message_text_251": "Edit Message Text",
        "mock_ilia_university_252": "Ilia University",
        "mock_tbilisi_state_univer_253": "Tbilisi State University",
        "mock_apartment_options_ar_254": "Apartment options are excellent, fully furnished and prices are very suitable for student budgets in Tbilisi",
        "mock_error_connecting_to__255": "Error connecting to server when adding service",
        "mock_saudi_arabia_256": "Saudi Arabia",
        "mock_alert_published_succ_257": "Alert published successfully",
        "mock_nationality_258": "Nationality",
        "mock_jordan_259": "Jordan",
        "mock_bathroom_with_wonder_260": "Bathroom with wonderful view from balcony",
        "mock_news_published_succe_261": "News published successfully",
        "mock_add_points_262": "Add Points",
        "mock_thank_you_very_much__263": "Thank you very much for the quick response and help with residency",
        "mock_ilia_state_264": "Ilia State",
        "mock_replied_265": "Replied",
        "mock_security_around_266": "Security around",
        "mock_notes_267": "Notes",
        "mock_service_added_succes_268": "Service added successfully to services list",
        "mock_immediate_move_in_269": "Immediate Move-in",
        "mock_under_review_270": "Under Review",
        "mock_available_for_reques_271": "Available for request",
        "mock_student_blocked_and__272": "Student blocked and chat closed successfully",
        "mock_explain_housing_and__273": "Explain housing and booking details",
        "mock_group_of_youth_274": "Group of Youth",
        "mock_hello_customer_servi_275": "Hello Customer Service",
        "mock_browse_housing_scree_276": "Browse housing screens for photos and full details",
        "mock_provide_comfortable__277": "Provide comfortable cars for reception upon your arrival in Tbilisi",
        "mock_university_of_georgi_278": "University of Georgia",
        "mock_edit_message_279": "Edit Message",
        "mock_this_account_has_bee_280": "This account has been blocked by customer service management and new messages will not be received",
        "mock_to_281": "To",
        "mock_hello_282": "Hello",
        "mock_open_chat_with_stude_283": "Open Chat with Student",
        "mock_archived_284": "Archived",
        "mock_university_285": "University",
        "mock_delete_286": "Delete",
        "mock_requested_service_287": "Requested Service",
        "mock_is_there_a_matching__288": "Is there a matching student currently ready for immediate move-in?",
        "mock_reem_ahmed_289": "Reem Ahmed",
        "mock_modern_studio_290": "Modern Studio",
        "mock_attached_link_291": "Attached Link",
        "mock_repairing_water_leak_292": "Repairing water leaks and plumbing maintenance",
        "mock_website_link_or_onli_293": "Website link or online file",
        "mock_dollars_per_person_294": "Dollars per person",
        "mock_delete_message_295": "Delete Message",
        "mock_are_you_sure_you_wan_296": "Are you sure you want to permanently delete this alert?",
        "mock_khaled_abdullah_297": "Khaled Abdullah",
        "mock_nationality_298": "Nationality",
        "mock_working_elevator_299": "Working Elevator",
        "mock_are_you_sure_you_wan_300": "Are you sure you want to delete this university?",
        "mock_two_hours_ago_301": "Two hours ago",
        "mock_yes_302": "Yes",
        "mock_fast_fiber_optic_int_303": "Fast Fiber Optic Internet",
        "mock_interactive_local_st_304": "Interactive Local Storage Mode"
    }
};

let currentLang = localStorage.getItem('admin_lang') || 'ar';

function toggleLanguage() {
    currentLang = currentLang === 'ar' ? 'en' : 'ar';
    localStorage.setItem('admin_lang', currentLang);
    applyLanguage();
}

function tr(arText) {
    if (currentLang === 'ar') return arText;
    
    // Normalize string to ignore multi-line whitespace
    const norm = (str) => str.replace(/\s+/g, ' ').trim();
    const search = norm(arText);
    
    // Find key by searching the 'ar' dictionary for the exact text
    const entries = Object.entries(translations['ar']);
    for (let [key, val] of entries) {
        if (norm(val) === search) {
            return translations['en'][key] || arText;
        }
    }
    return arText; // Fallback
}

function applyLanguage() {
    document.documentElement.lang = currentLang;
    document.documentElement.dir = currentLang === 'ar' ? 'rtl' : 'ltr';
    
    // Also re-render dynamic tables so they get translated
    if (typeof renderApartments === 'function') {
        renderStats();
        renderApartments();
        renderServices();
        renderRequests();
        renderStudents();
        renderUniversities();
        renderDistricts();
        renderReviews();
        renderNews();
        renderNotifications();
    }

    // Dynamically walk text nodes in the body and translate them!
    walkAndTranslate(document.body);
}

// Store original Arabic text on elements to allow flipping back
function walkAndTranslate(node) {
    if (node.nodeType === 3) { // Text node
        const text = node.nodeValue.trim();
        if (text) {
            if (!node.parentElement.hasAttribute('data-orig-text')) {
                // Store the exact original value
                node.parentElement.setAttribute('data-orig-text', node.nodeValue);
            }
            const orig = node.parentElement.getAttribute('data-orig-text');
            const translated = tr(orig);
            
            // Just replace the text content of the node entirely to avoid whitespace matching issues
            if (translated !== orig && currentLang === 'en') {
                node.nodeValue = translated;
            } else if (currentLang === 'ar') {
                node.nodeValue = orig;
            }
        }
    } else if (node.nodeType === 1) { // Element node
        // Translate placeholders
        if (node.hasAttribute('placeholder')) {
            const text = node.getAttribute('placeholder').trim();
            if (text) {
                if (!node.hasAttribute('data-orig-placeholder')) {
                    node.setAttribute('data-orig-placeholder', node.getAttribute('placeholder'));
                }
                const orig = node.getAttribute('data-orig-placeholder');
                const translated = tr(orig);
                if (translated !== orig && currentLang === 'en') {
                    node.setAttribute('placeholder', translated);
                } else if (currentLang === 'ar') {
                    node.setAttribute('placeholder', orig);
                }
            }
        }
        
        if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE") {
            for (let i = 0; i < node.childNodes.length; i++) {
                walkAndTranslate(node.childNodes[i]);
            }
        }
    }
}

// Ensure language applies on load
document.addEventListener("DOMContentLoaded", () => {
    if (currentLang === 'en') {
        applyLanguage();
    }
});
